### ISSUE TITLE
Get deploy on heroku via travis working

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#10]
branch: heroku
`Skipping a deployment with the  provider because this branch is not permitted
`

**Comment by gyachdav** [comment]
I got here through a reference from issue #8 yet it is unclear to me how we can view your demo site. If you deployed to Heroku and added me to as a collaborator then it would be nice to understand how and where i can view the site. The link I got from Heroku send me to an app dashboard and all I can get from there is a very disappointing hello world page. 

bottom line: we need to see a demo site. soon!

**Comment by yashha** [comment]
You are right we are still not have a demo site
I will work on it today.
I thought i add you to heroku, so you give heroku access to the github.
But then I tried a way using travis to deploy to it.
It's not working yet.
I will continue to try to use travis.
I will post the url on the readme, when it is working.

**Comment by gyachdav** [comment]
thanks. more importantly post the link on this issue.

**Comment by yashha** [comment]
Working 
https://got-stats.herokuapp.com/

**Comment by gyachdav** [comment]
thanks when should we expect to see the actual app you were working on? right now just gives me the beginning of a site layout. 
![screen shot 2016-03-11 at 2 50 36 pm](https://cloud.githubusercontent.com/assets/4074881/13713785/c1ebed2a-e798-11e5-8db0-2bf066ee6ac5.png)

**Comment by yashha** [comment]
Unfortunately that's all we got at the moment.
Next thing to do is creating the a layout looking like our mockup
https://github.com/Rostlab/JS16_ProjectF/blob/mockups/Mockups/Home.jpg

**Comment by gyachdav** [comment]
Let us know when there's some content we can give feedback on
