### ISSUE TITLE
Implement Twitter Sentiments

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#101]
NPM Package: https://github.com/Rostlab/JS16_ProjectF/issues/31
https://www.npmjs.com/package/gotdailysentiment

ToDo (Implementation):
- [ ] Character-Detail Page
- [ ] Rankings
- [ ] ? Home ?

**Comment by jorjo1** [comment]
I think that @mina-zaki should help us out here and connect this with the package on our side.

**Comment by jorjo1** [comment]
@yashha can you please help us out here?

**Comment by julienschmidt** [comment]
Here is Group 4's API draft: https://github.com/Rostlab/JS16_ProjectD_Group4/issues/25#issuecomment-199776355

Please comment on it!

**Comment by yashha** [comment]
#122
