### ISSUE TITLE
Enable a web api for the map

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#105]
I forgot who is the router person for F so I'm just assigning this to @mammuth feel free to re-assign.

We would probably want to distribute links that will load the map + some characters + paths. 

for instance I would like to show that Stannis Baratheon and Renly Baratheon meeting in S2E8 resulted in Renly's death (see screen shot). I would encode this into the URL such that we would have the following api:

https://got-stats.herokuapp.com/#/map?character='Renly Barathon'&character='Stannis Baratheon'&begin_time_line='s1e1'&end_timeline='s2e8'

![screen shot 2016-03-21 at 11 40 48 am](https://cloud.githubusercontent.com/assets/4074881/13924350/599643b4-ef5a-11e5-9362-0b568655e039.png)

@AlexBeischl @tPiffrader @mbandle

**Comment by bandle** [comment]
@yashha 
You can use our API functions to accomplish that. When something is missing, just tell us

**Comment by sacdallago** [comment]
@gyachdav too much API here. It's just a _route_ with url-encoded queries :D

**Comment by gyachdav** [comment]
yup should've been "expose the map's API" but okay I think they got the message

**Comment by yashha** [comment]
Looks doable ;)

**Comment by yashha** [comment]
done

**Comment by yashha** [comment]
https://got-stats.herokuapp.com/map?character=Renly%20Baratheon&character=Stannis%20Baratheon&begin_time_line=s1e1&end_time_line=s2e8

**Comment by gyachdav** [comment]
Nice, thanks @yashha!

Minor bug: https://got-stats.herokuapp.com/characters/Walder%20Frey 
brings up Walder Frey (son...) in the map and not the original Lord of the Crossing. 

@mbandle @AlexBeischl can you also take a look?

**Comment by yashha** [comment]
The problem is there is no lord
https://got-stats.herokuapp.com/characters/?search=Walder%20Frey&page=1
Or not the right image

**Comment by gyachdav** [comment]
i think that the map' API will load with the first Walder Frey it find if there are many chars that start with this name. @mbandle please change to first look up exact match and then fall back to string expansions.

**Comment by sacdallago** [comment]
The guys from A should have implemented a strict attribute that you can pass to the call... @Adiolis ?
