### ISSUE TITLE
Don't show PLOD for dead characters

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#107]
while amusing, showing PLOD for dead characters doesn't make us look good. please enable a check for that.

**Comment by mina-kleid** [comment]
@gyachdav Isnt this related to the guys implementing PLOD, we are just presenting what they provide us with ?

**Comment by nicoladesocio** [comment]
in the json file there is a field for the current status ("status") and a field for the predicted status ("status_pred").

edti: since you use the functions and not the json file, we'll need t provide functions for that,and maybe a field in the database?

**Comment by mina-kleid** [comment]
@nicoladesocio currenty the call to the api (https://got-api.bruck.me/api/characters/plod/:count) returns me only characters. 
Yes providing an api to get PLOD without the dead should work.

**Comment by nicoladesocio** [comment]
Done, now I'll create an issue in project A, to ask if they can provide the API

**Comment by mammuth** [comment]
So this can be closed, since as soon as A implemented that feature we will get PLOD's only for alive characters, right? 
https://github.com/Rostlab/JS16_ProjectA/issues/106
