### ISSUE TITLE
Static content editing

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#110]
We would like to be able to edit static content on the site without hardcoding the text into your source. 

We propose you implement one of the following two solutions:
1. create a db (relational would be better/faster than NoSQL) and pull the content from there. We will just use our credentials (which you will share with us) to publish static content. 
2.  create a separate branch for static content files. You will pull the content from the files and we will just edit the text in the files. Then we will send a PR, you merge to master and @sacdallago will then pull the rev on the production box. 

Both options are fugly, but are yours to choose from.

**Comment by yashha** [comment]
I would try this one ;)
https://github.com/osnr/react-markdown-loader

**Comment by gyachdav** [comment]
Status? who should be assigned here? don't let this issue drag for too long.

**Comment by gyachdav** [comment]
We need a blog like capabilities the react-markdown-loader may be a nice alternative although seems to be a bit immature. 
another example i found is https://github.com/misterfresh/react-drive-cms although also not clear how far into development it is. 

Does react have a registry of recommended add-ons?

p.s. 
another interesting options:
1.  http://moox.io/statinamic/
2. http://braddenver.com/blog/2015/react-static-site.html

**Comment by yashha** [comment]
It looks cool http://misterfresh.github.io/react-drive-cms/#!/home
But i think it's difficult to setup

Maybe thats more easy http://moox.io/statinamic/

**Comment by yashha** [comment]
Drive based cm would be really interesting though

**Comment by gyachdav** [comment]
Oh man this task should've been picked up by the person who is suppose to pick it up so.... @Andrew094 you're it! this one is URGENT!

**Comment by gyachdav** [comment]
@yashha very nice of you to pick up tasks, but there are other members in this group and we expect everyone to pull their weight. Reassigned to @Andrew094

**Comment by Andrew094** [comment]
@gyachdav Can you explain which static content you mean? 
at the moment I only consider the about page and the about section in the footer as static.

**Comment by gyachdav** [comment]
We would wanna have a block of text on the:
- homepage (maybe even two block of texts)
- about page 
- character pages (optional)
- footer
