### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#119]
- [x] Show version number (take automatically from build) 
- [x] show CC4 license(and link to [CC4](https://creativecommons.org/licenses/by/4.0/))

**Comment by Andrew094** [comment]
as for the version number we haven't used any tags so far to generate a verion string like "v1.0", instead
when running
git describe --all --long
on develop you would get something like:
heads/develop-0-g1506382

so I think this is more a configuration thing in the build system

**Comment by gyachdav** [comment]
cool do whatever you need to make it work then :+1:

**Comment by yashha** [comment]
https://api.github.com/repos/Rostlab/JS16_ProjectF/tags

**Comment by Andrew094** [comment]
and how is this version number increasing ?

**Comment by yashha** [comment]
Look again, I made a new label. :)

**Comment by sacdallago** [comment]
@gyachdav the licence in most repos is CC3

**Comment by gyachdav** [comment]
CC3 it is then.

**Comment by jorjo1** [comment]
@gyachdav @sacdallago are third parties allowed to use our projects for commercial purposes? This is an important milestone while including the license.

**Comment by sacdallago** [comment]
There's a cascade of licenses which gives me the impression that being in CC3 saves us from violating other licenses and also gives us enough accountability in case people reuse our stuff. Commercial purposes goes back to the cascade of licenses :D

**Comment by gyachdav** [comment]
Currently the footer says " 2016 Game of Thrones" note that the name Game of Thrones is copyrigthed and we cannot use it.  

It should really say  "2016 A Song of Ice and Data" instead

**Comment by yashha** [comment]
and version with spaces and an - seperated

**Comment by gyachdav** [comment]
About
- [x] About got.show - https://github.com/Rostlab/JS16_ProjectF/issues/234
- [x] Credits - https://github.com/Rostlab/JS16_ProjectF/issues/19
- [x] Attributions - https://github.com/Rostlab/JS16_ProjectF/issues/65
- [x] [JavaScript Technology 2016](https://rostlab.org/owiki/index.php/Javascript_technology_2016) 
- [x] rostlab.org
- [x] tum.de

Contribute
- [x] Developers - https://github.com/Rostlab/JS16_ProjectF/issues/228
- [x] Contribute - link to https://editor.got.show/

Social 
- [x] Facebook
- [x] Twitter
- [x] Google+

Legal
- [x]  Imprint & Disclaimer - TUM legal statement
- [x] Privacy Policy - https://github.com/Rostlab/JS16_ProjectF/pull/229#event-611908709

Contact
- [x] Feedback - link to issues section of https://github.com/got-show @sacdallago will open relevant repo

**Comment by sacdallago** [comment]
On it

**Comment by sacdallago** [comment]
https://github.com/got-show/general/issues

**Comment by gyachdav** [comment]
Use the Imprint and Disclaimer text from:

https://docs.google.com/document/d/1c7fnPBgdlkfd0H1HCr7y-GO-8bkqSzXDcYrIBkFmAdQ/edit?usp=sharing
