### ISSUE TITLE
Loading image

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#120]
I have a suggestion for a character list loading image:
http://all-free-download.com/free-vector/download/set_of_realistic_swords_and_knifes_311832.html

one sword + circle animation ;)

**Comment by jorjo1** [comment]
Assign me! We will discuss on it later.

**Comment by mammuth** [comment]
If we cache the characters (or even better, @sacdallago puts an http cache in front of react) we probably don't need any loading images
See the caching issue: #159
