### ISSUE TITLE
Fix map design issues

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#124]
- [x] hide characters bar on mobile devices
- [x] fix width of map on detail page
- [x]  #17
#17

> mbandle:
> What do you think about changing the CSS property `height` in .gotmap-dropdown to `max-height` 
> This would fix this minor issue
> ![bildschirmfoto 2016-03-20 um 23 40 21](https://cloud.githubusercontent.com/assets/11232638/13907717/204900f2-eef5-11e5-9398-2c02a70dd1df.png)

**Comment by mammuth** [comment]
_hide characters bar on mobile devices_
at least the search bar should probably stay there (maybe moved above the map itself).

**Comment by sacdallago** [comment]
@mammuth https://github.com/Rostlab/JS16_ProjectC_Group10/issues/181

**Comment by sacdallago** [comment]
P.S.: that _is_ working: http://map.got.show
Don't know if the package is at its last update though.

**Comment by mammuth** [comment]
Nice that we have duplicate issues...
<img width="362" alt="screen shot 2016-03-26 at 20 06 54" src="https://cloud.githubusercontent.com/assets/3121306/14062123/13eb9c04-f394-11e5-8311-c2331543b647.png">
PS: In the latest map package I pulled today when I started working on this, the map wasn't mobile friendly yet.

**Comment by sacdallago** [comment]
:D My bad, I was watching this issue and was convinced you were having other responsive problems. Should have pulled out that issue earlier... I'm a terrible, terrible procast... **Project Manager**! :laughing: 
Anyway according to npm the version on npm is up to date (9h ago): https://www.npmjs.com/package/gotmap

sure you `npm update`ed?

**Comment by mammuth** [comment]
Jep. I started this morning before that version was released :stuck_out_tongue_winking_eye:

**Comment by sacdallago** [comment]
fififi I feel so guilty now :eyes:
