### ISSUE TITLE
Create fallback page for No-JS users

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#127]
Title says it all. We should have this case covered, when someone has forbidden JS on his browser.

Maybe this: http://reactjs.net/guides/server-side-rendering.html

**Comment by yashha** [comment]
I thought about integrating server-side rendering if it works, that would be seo friendly, too.

**Comment by yashha** [comment]
But now I think even with serverside rendering we still need to think about non js users.

**Comment by mammuth** [comment]
I'd suggest just making a simple note saying "to use this page please enable Javascript in your browser"...

**Comment by sacdallago** [comment]
@mammuth is right. Com'on, even opera mini on my phone is semi-js compatible :D
