### ISSUE TITLE
Not stagable

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#147]
I made a mistake and pulled in my currently not stagable server.js to develop
I'm still waiting for https://github.com/Rostlab/JS16_ProjectD_Group5/issues/60
I'll probably tweak the server.js in the next hour, so we can stage with own dummy d5 data.

**Comment by yashha** [comment]
I thought about all this and there is another problem
We have no local mongodb on our heroku
And d4 requires one

**Comment by gyachdav** [comment]
do they really need the db? @kajo404, I thought you said you just got rid of your mongodb. if not then you'll have to stage this on mlab. Heroku charges for mongo.

**Comment by gyachdav** [comment]
oops @kajo404 is actually D4. never mind then @kajo404 you were dragged into this by accident :laughing: 

okay @yashha just ask the E rep for D5 to deploy their mongo to mlab then.

**Comment by kajo404** [comment]
you still got something mixed up ;) I am D5 but we do not use mongodb anymore

**Comment by gyachdav** [comment]
right whatever @kajo404 said :laughing:

**Comment by yashha** [comment]
not @kajo404  but @julienschmidt :)

> do they really need the db? @kajo404, I thought you said you just got rid of your mongodb. if not then you'll have to stage this on mlab. Heroku charges for mongo.

**Comment by julienschmidt** [comment]
Yes. We store our tweets there and we never wanted to get rid of that. You really don't want a full re-crawl every time again. It takes a few hours... 
Where you host this is up to you / project E. We just write the code :wink:

**Comment by julienschmidt** [comment]
Does heroku charge for CPU time or (outgoing) HTTP requests too?

**Comment by yashha** [comment]
Heroku needs a credit card, that is what I noticed.

Ok then, @CavidSalahov  can you provide a patch for your package to give us the abillity to provide a db in the config?

**Comment by julienschmidt** [comment]
Take a look at [`defaults.json`](https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/defaults.json). There is already an URI for the MongoDB. You can overwrite every value by passing an object with that attribute to [`cfg.extend(obj)`](https://github.com/Rostlab/JS16_ProjectD_Group4#gotsentimental.cfg.extend).

**Comment by yashha** [comment]
Ah awesome! Thanks :)
It should be described in the docs though ;) @CavidSalahov

**Comment by julienschmidt** [comment]
Well.. it is already in the docs :wink: 

I'm currently running a full crawl (it will take a few hours more...). I can provide you a dump of all tweets for testing purposes. Maybe you can also dump it in the MLab DB somehow.

Just write me an email to ihatemongodb at js-web dot eu and I'll reply with a link later.

**Comment by yashha** [comment]
Your right, I just needed this :)
`mongodb://username:password@host:port/db`

OK, thanks

**Comment by julienschmidt** [comment]
Is it possible to write files on Heroku? (which then are read & served again)

Currently we're generating static CSV files. If it isn't possible on Heroku, we'd have to write the CSV data to MongoDB too

**Comment by yashha** [comment]
I think it is possible.
I try it today
Are they numered from 0 to x ?

**Comment by julienschmidt** [comment]
nope.
episodes.csv
ramsay-snow.csv etc

Probably we would also need subfolders for each character where we store more precise data per month or even day

**Comment by julienschmidt** [comment]
https://github.com/Rostlab/JS16_ProjectD_Group4/pull/70

**Comment by julienschmidt** [comment]
> Changes to the filesystem on one dyno are not propagated to other dynos and are not persisted across deploys and dyno restarts. A better and more scalable approach is to use a shared resource such as a database or queue.

https://devcenter.heroku.com/articles/how-heroku-works#dyno-manager

It takes some time to generate all the files. Is it OK to generate them on each start?

**Comment by yashha** [comment]
Yea no problem, and we use one dyno
