### ISSUE TITLE
character search - pagination

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectF#150]
The pagination currently shows only 3 pages [prev, current, next]. It should Also provide a link to the first and last page:

[1] .... [41] **[42]** [43] ... [1337]

**Comment by jorjo1** [comment]
We did assume it is not necessary to put the first and the last page. 
We will think this through, again, tho.

**Comment by yashha** [comment]
I would like to have a first and last page button, its currently really empty :)

**Comment by julienschmidt** [comment]
And impractical. Let's say you have the ranking implemented and I'm looking for the least popular character. I certainly would stop clicking the next page after 2-3 pages when I don't even know how many pages there are.

**Comment by sacdallago** [comment]
Thanks for noticing this. The way it is now is also kind of misleading :D I thought there would only be 3 pages :P I was like *woah, they really rationed well and 2000 chars fit sooooo nicely into three pages" :sun_with_face:
