### ISSUE TITLE
MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#156]
$ npm start

> js16seminar@0.0.1 start /Users/guyyachdav/Sites/JS16_ProjectF
> webpack-dev-server --progress --inline --content-base public  --history-api-fallback

{ [Error: Cannot find module './config/config.json'] code: 'MODULE_NOT_FOUND' }

Is that critical?

**Comment by yashha** [comment]
Its because from now on you need a config file to contribute. :)
