### ISSUE TITLE
Make webpack-dev-server runnable combined with the server 

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#158]
At the moment the webpack-dev-server wont start the server.js
So we wanna integrate it into the server.js so it starts the dev server in the background and we have all route available while developing.

**Comment by sacdallago** [comment]
Maybe an **E** person can help? They are experts in webpack by now :D @TheZoker @Emiliyana 

CC @AlexMoroz @CavidSalahov @jonny3576 @AngeKouemo

**Comment by yashha** [comment]
Is done already :)
I worked on it in the night :D
#158

**Comment by sacdallago** [comment]
:D and sleep, sometime? :D

**Comment by yashha** [comment]
Or woke up right now :D
