### ISSUE TITLE
Heading for map in character page

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#160]
The map view is missing a heading. 

Should say something like:

Places associated with Character_Name

**Comment by jorjo1** [comment]
@gyachdav sorry for asking but I got a bit confused: What should "Places associated with" stay for? Is it some kind of an area we need to pull in?

**Comment by gyachdav** [comment]
Edited the issues. This is just the heading that should come above the map. Should say Places associated with character_name where character_name is the character entry you are shown great on the page e.g on Jon snow page you will show

Places associated with Jon Snow

**Comment by jorjo1** [comment]
All right. There was actually some title, but it was never to be seen because of the map positioning. This is now a fact in #164
