### ISSUE TITLE
Overlapping text in About

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#165]
![screen shot 2016-03-27 at 3 36 06 pm](https://cloud.githubusercontent.com/assets/6240943/14065626/b74a3368-f431-11e5-9e28-0043d2d85005.png)

It's platform independent ;)

**Comment by gyachdav** [comment]
Don't worry about that. It'll be completely redesigned.

**Comment by jorjo1** [comment]
Hello @gyachdav, do you have something in mind? Some mockups maybe? What I understand from your comment is that either you will share some ideas or we are responsible for this.

**Comment by gyachdav** [comment]
Hey yes sorry for not elaborating. Tomorrow we want to have a website design meeting and we want representative  from F to participate. In the meeting we will all decide on website structure (sections sub sections etc ) and how would pages look like. Currently we plan to talk around 9pm Munich time but this may shirt. Stay tuned.

**Comment by jorjo1** [comment]
I'm in.

I'm also available in the afternoon, so you can choose the most convenient time. :alarm_clock:

**Comment by gyachdav** [comment]
We will have the meeting at 9pm CET. @jorjo1 what's your skype ID?

 @sacdallago @goldbergtatyana

**Comment by jorjo1** [comment]
I am jorjo.1 in skype :D

**Comment by jorjo1** [comment]
But I think it'll be much more better if we take google hangouts or jitsi - we just share a link and anybody could join. Also the older versions of Skype don't allow screensharing or multi-cam.. :see_no_evil:

**Comment by gyachdav** [comment]
yeah i know but hangouts already failed us once (the link didnt work) so we'll just use good old skype with its basic set of features

**Comment by mammuth** [comment]
I'm not sure I get it in time, I'll ping @jorjo1 to add me, as soon as I'm available. :blush:

**Comment by yashha** [comment]
skype: yasarkkk, I would like to attend, maybe I have some ideas

**Comment by jorjo1** [comment]
We are here, just testing: https://meet.jit.si/GoTJS

**Comment by sacdallago** [comment]
The text before deviated a bit from the original purpose of this issue. After yesterday, where does this _issue_ stand?

**Comment by gyachdav** [comment]
We will discuss this on Thursday in part 2 of the website design meeting

**Comment by gyachdav** [comment]
I believe this can be closed. @sacdallago  please confirm and close.

**Comment by yashha** [comment]
It is not fixed yet

**Comment by gyachdav** [comment]
it wont be fixed since we're coming up with a new Credits page as discussed here

https://docs.google.com/document/d/1TxGVoVNiqhclnwG5pw8-iRYljKpmjEn91FyTw51IyWk/edit#bookmark=id.ahyqwvxwprxt

**Comment by sacdallago** [comment]
But it's still important to keep this in mind. With that font, it can happen.
But yes, I'll have an eye open on that, please @gyachdav also remember
