### ISSUE TITLE
Landing Pages Discussions

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectF#169]
Hey Project F!

As promised, here's my next issue. I'm creating at least 5 landing pages from [this idea pool over here](https://groups.google.com/forum/#!topic/javascript-technology-2016/ziXPdSGQjqE) and need someone to help out with design & actual implementation!
### What's gonna be on those pages?
- SEO text
- Pictures / statistics / graphics
- views from our tools

I'll provide you with content-filled .html pages (and a simple wireframe) which you can then add to our website. In the end, those pages are going to be structured quite similarly, so best case we make a nice template once and the rest is gonna be done really quickly.

I further propose this schedule so we'll definitely be done before launch:
### Schedule

**By ~~29.~~ 30.03.2016:** (postponed 1 day, blame @marcusnovotny)
- [x] Content of first landing page is ready <s>as an .html file</s> & submitted to Group F

**By ~~01.~~ 02.04.2016:** (postponed 1 day)
- [x] First landing page is readily designed & can be used as a template for the following pages

**By 03.04.2016:**
- [x] Content for all landing pages is ready & submitted to Group F

**By 07.04.2016:**
- [x] All landing pages are readily designed & integrated into the website.

**10.04.2016 Website Launch**

Volunteers welcome. Looking forward to collaborating with you! 

Marcus

**Comment by sacdallago** [comment]
CC @Rostlab/js_cs_sose_2016_students

**Comment by mammuth** [comment]
Wanna have a hangout this evening to discuss your plans? 
Maybe with some other guys from F (@jorjo1)?

Furthermore plain html drafts won't make anything easier for us I'm afraid, because we need to "translate" them in react components :wink:
Or we serve those landing pages without react, but this obviously only works if we're not using any of our existing components. 
But let's discuss those stuff this evening. 

Can we add you to our slack team?

**Comment by marcusnovotny** [comment]
Sure I'm home today

**Comment by jorjo1** [comment]
I am there!

**Comment by togiberlin** [comment]
Hello all, as I've written [here](https://github.com/Rostlab/JS16_ProjectA/issues/77), I'm also part of this task. However I have 3 exams (on 31st, 1st and 6th.)
After the 1st April I should be there for support regarding the statistics visualization.

**Comment by marcusnovotny** [comment]
@togiberlin sorry for not getting in touch with you again until now, I'll send you the first page these days so you can have a look after the 1st and we can discuss what graphic to use together! Focus on your exams first :)
@mammuth @jorjo1 Would 7 PM be convenient for you? If there are no objections I'll post a hangout link shortly beforehand.

**Comment by yashha** [comment]
I would be there too :)

**Comment by marcusnovotny** [comment]
[Be my guests!](https://hangouts.google.com/call/cpxgcpl4ircsffskkuvykaaykue)

@mammuth @jorjo1 @mammuth

**Comment by mammuth** [comment]
Basic summary:
- Our "normal" website-pages probably suck in terms of SEO, due to the lack of meaningful text
- Essentiall: 2-3 Keywords per page. So we should focus the landing pages on Character/House + "Game Of Thrones"
- 300-400 words per landing-page
- We need catchy stuff like infographics to not lose the visitor due to boring SEO-text
- The 300 words need to be well structured and put into section with well chosen headings. Furthermore there should be an image per section so the text is nicer to read.
- @marcusnovotny is writing a text-draft for Jon Snow tomorrow, that I will check out, to maybe find out some improvements
- For the infographics Marcus is staying in contact with @togiberlin 

Did I miss something guys? :relaxed:

**Comment by gyachdav** [comment]
Status?

The [promo plan](https://docs.google.com/document/d/1CH33DqIg3oPbbgIIhXRgWFPb7xGkD7cq5YDx32n70PI/edit) says:

By 29.03.2016:
    \* Content of first landing page is ready as an .html file & submitted to Group F 

Was this milestone completed?

**Comment by marcusnovotny** [comment]
@gyachdav No, I'm currently on it. Informed @mammuth over slack last night that I didn't make it and we'll postpone the first two deadlines by a day. Haven't changed it here yet, mea culpa, but we'll keep you updated!

**Comment by gyachdav** [comment]
Thanks for the quick response. Please keep track of those deadlines and let us know If something changes so we can readjust and don't fall completely out of schedule.

**Comment by marcusnovotny** [comment]
Sure! As the initiator I'm terribly embarrassed that it's me who already postpones a deadline, but my own project (D4) is keeping me super busy at the moment. Shouldn't influence the final deadline though, as long as Project F has enough time to finish the template before I submit the other landing pages (which is still the case), that's why I didn't notify you earlier.

**Comment by marcusnovotny** [comment]
Here's the Jon Snow Landing page. Decided to post it right here, more information on the bottom.

---

**[Meta Title]** Why Jon Snow is not dead - Game of Thrones
**[Meta Description]** We at got.show set up our own machine learning algorithm to predict Jon Snow's fate and came to surprising conclusions!
**Optimized for Keywords:** Jon Snow, Game of Thrones, got

---

# H1: Why Jon Snow is not dead

[“The past is already written, the ink is dry”](https://www.youtube.com/watch?v=IxI8aPISq8I) – so says the teaser for the sixth season of the popular TV show Game of Thrones. And until recently, that’s what we at **got.show** believed too. 9 long months after we saw our favourite character **Jon Snow** join his father up in GoT heaven in the season 5 finale “Mother’s Mercy” however, we have reason to believe that he’s going to stick around on earth with the rest of us for a little longer. You don’t think so? Well, then **you know nothing, Jon Snow.**

## H2: 4 reason Jon Snow is still alive

### H3: Our very own machine learning algorithm suggests it.

We at **got.show** are firm believers that artificial intelligence & machine learning can have a more beneficiary impact on humanity than [embarrassing us at our own games](http://www.theverge.com/2016/3/15/11213518/alphago-deepmind-go-match-5-result) – that’s why we **created an algorithm that calculates Game of Thrones characters’ likeliness of death**! Luckily, **Jon is only at 11.6%**, which is overall pretty low. You’ll be glad to know that [Ramsay Bolton](https://en.wikipedia.org/wiki/Ramsay_Bolton) for example is at over 60%! Furthermore, being Lord Commander of the Night's Watch makes him one of the safest guys in all of Westeros, since it is the title with the lowest death rate in the series. [Read more about our awesome Life & Death Predictions here!](https://got-stats.herokuapp.com/ranking)

> Placeholder 1) Infographic Image @togiberlin
> Culture, title & gender play a huge role in terms of survival chances on Games of Thrones. 

### H3: He is way too popular to be killed off.

I know, I know – being popular couldn’t save a lot of our other favourite Game of Thrones characters, but with Jon it’s different. Just see what an outrage the season 5 finale caused on Twitter with our Twitter Sentiment Analysis App – and then think about the gigantic plot twist of bringing him back to the living!

>  Placeholder 2) Twitter graph.
> How does Twitter feel about Jon Snow? See for yourself with our Game of Thrones Sentiment analysis.

### H3: Kit Harington (Jon Snow’s actor) has been on set for the sixth season Game of Thrones!

[Read about it in the independent.](http://www.independent.co.uk/arts-entertainment/game-of-thrones-season-6-not-only-is-jon-snow-alive-but-he-s-wearing-stark-armour-a6669801.html). And if that’s still not enough for you, what do you think about this official HBO poster? 
![](http://www.hbo.com/custom-assets/img/series/game-of-thrones/season-6-tease.jpg)

> Alt Text: Official Announcement poster for the sixth season Game of Thrones, featuring Jon Snow.

### H3: He just can’t be dead.

I can’t even. Who’s going to care for Sam & Gilly? Who will handle the wildlings? Let me tell you one thing: If Leonardo di Caprio can drag himself through the freezing cold for weeks after [fighting with a goddamn grizzly bear](https://en.wikipedia.org/wiki/The_Revenant_%282015_film%29), why shouldn’t Kit Harington survive a minor stabbing, heh?

**Still not convinced?** Then you’ll be glad to hear that the season 6 premiere of Game of Thrones is going to air on the 24th April 2016 already - [soon we will know.](http://www.daystillgameofthrones.com/)

## H2: **Follow Jon’s <s>last</s> latest steps here!**

> Placeholder 3) GOT Map
> Alt Text: Follow Jon Snow’s footsteps with our Game of Thrones map!
> Shortly after leading the wildlings to Castle Black to save them from the nearing White Walkers, Jon had to learn about Stannis Baratheon’s fate from Melisandre. Then the unthinkable happened. Where will we see him next? Stay tuned at got.show

---

# About the Placeholders

## Placeholder 1) Infographic about PLOD contributing features

@togiberlin Please make an infographic referencing the stats from this [ProjectB issue](https://github.com/Rostlab/JS16_ProjectB_Group6/issues/60#issuecomment-201949253). I’d only focus on Culture, Title & Gender info. Maybe emphasize Jon Snow’s survival change explicitly again when it comes to the Lord Commander of the Night’s Watch.
Project F will be able to give you some guidelines on size & formatting while they’re arranging the template page.

## Placeholder 2) Twitter sentiment

Here we’ll just serve a view from ProjectD_Group4’s Twitter graph (my group). I’ve added startDate & endDate parameters to the function that creates the graph, so you can specify the default date Range when loading the tool. I’d go for something around May 20 – June 20 2015 (season finale aired on June 14th)

## Placeholder 3) GOT Map

Just our amazing Map with Jon Snow added as a character. I’d show all the available data.

---

# Styling Guide

We talked about styling the Landing Pages & me proposing a wireframe together. Since you’re using React, me providing a regular .html page wouldn’t have made sense. Hope you don’t mind me pre-arranging it here – I couldn’t think of an easy solution that allows both easy formatting and element placement without screwing up the text too much.
I also didn’t make a wireframe due to time constraints, but I’d go for a simple layout, [like the one buzzfeed’s using:](http://www.buzzfeed.com/chelseamarshall/aber-dafuer-musste-ich-staendig-pinkeln#.cve1Kon05) Header, Content (Image / Tool), Text, Repeat. If you don’t wanna arrange it all vertically, you can also move the content to the sides or wherever else you’d like ;)

Thanks for reading. Looking forward to your feedback & suggestions! We should make multiple iterations for the pages, so don’t hold your criticism back.

**Comment by gyachdav** [comment]
Laughed my ass off!! Nice work Marcus. 

In our web design meeting today it was decided that the landing pages should get into the static branch so we should all be able to edit them as we go. Please start a "static" branch and put the landing pages on there.  Let me know when done do I can push my proposed edits. 

Please verify with f where exactly the static pages should go in their tree.

**Comment by marcusnovotny** [comment]
Thanks! Good idea. I think F has to start the branch though, I have no access

**Comment by mammuth** [comment]
@jorjo1 are you starting this branch for marcus and guy?

**Comment by sacdallago** [comment]
@marcusnovotny I'll add you to the collab of F now

**Comment by marcusnovotny** [comment]
Will work on the remaining pages tomorrow. Where do you want me to put them and in which format?

Any progress on the first page / template?

**Comment by marcusnovotny** [comment]
Bad news from my part: I didn't get to the pages yet. I was fully occupied with D4 until yesterday and only started with the House Stark Page tonight. I hope to deliver on Tuesday since I'm completely booked out tomorrow. We can adjust your delivery deadline accordlingy. Sorry for the inconvenience, but I'm trying my hardest

In the meantime: I've started up a Landing Page branch and put the Jon Snow page on there in the static directory, as an .md file in GitHub markup. I will continue to do so with the remaining pages. @togiberlin can add his infographic for the page after his exam.

Furthermore, I understand that you are extremely busy right now - I saw all the issues on your repo - but it would be nice to get some response from you, even if it's just "couldn't be done yet". That's totally fine as long as we stay in touch and manage the deadlines.

Paging @mammuth & @jorjo1 here - put whoever's responsible from your project as the new Assignee & give me a heads up on the first page and possible complications :wink:

See you!

**Comment by togiberlin** [comment]
@marcusnovotny Ok, I read your post. I can offer you WhatsApp/Viber for direct updates, if necessary

**Comment by marcusnovotny** [comment]
@togiberlin No it's okay that's not high priority!

**Comment by marcusnovotny** [comment]
Have to reschedule again, I highly underestimated my workload this week.
I am definitely going to hand in the Stark Landing Page Wednesday night. For the rest the new deadline is "asap", hopefully until Friday. Daenerys Targaryen, House Lannister and one of those 3: George RR Martin OR Ramsay & Theon OR Stannis & Melisandre are still missing.

I'm sorry, but I'm operating at my limit currently. If there's anyone with free capacity that could take over 1-2 pages that would speed up the process a lot @gyachdav 

@ Project F: If I can help you out by formatting in another way than Git Markhub, please let me know too

**Comment by yashha** [comment]
@marcusnovotny Just use google docs or html, most important is the content
the mark up and design is just a matter of time investment, that can we do too.

**Comment by gyachdav** [comment]
no worries @marcusnovotny, let me know which topic you wanted me to pick up. Im currently working on the statistics page. https://docs.google.com/document/d/17VFx2gogagzMGQy1BOFpffUVfvSo8fHejDl2pNKMfvA/edit?usp=sharing

**Comment by marcusnovotny** [comment]
Thanks for your offer @gyachdav!  You can pick any of the remaining three (George Rr Martin, Melisandre & Stannis or Ramsay & Reek), up to you! Let me know if it works out :+1:

**Comment by marcusnovotny** [comment]
Pushed House Stark to the LandingPages branch

https://github.com/Rostlab/JS16_ProjectF/blob/LandingPages/static/house-stark.md

**Comment by gyachdav** [comment]
Thanks will go over this and the Jon snow one(did you push that one too?) over the weekend. Btw what's up with rickon?

**Comment by gyachdav** [comment]
I'll also do Ramsay and reek once I'm done with the stats page.

**Comment by marcusnovotny** [comment]
All files are in the /static directory of the LandingPages branch 

I barely know him tbh. Let me set up the other two first then I can add another paragraph! 

Thanks for helping me out! :+1:

**Comment by goldbergtatyana** [comment]
Thanks for the awesome job, @marcusnovotny! Once started reading, I just couldn't stop myself until I made it till the end of the landing pages. They are a bomb! :))

**Comment by togiberlin** [comment]
@gyachdav I wrote yesterday my last exam and from today evening, I'm pretty much free til Sunday.
I would pick your GOT Stats [Google Docs](https://docs.google.com/document/d/17VFx2gogagzMGQy1BOFpffUVfvSo8fHejDl2pNKMfvA/edit?pref=2&pli=1) and [Project B PLOD](https://github.com/Rostlab/JS16_ProjectB_Group6/issues/60#issuecomment-201949253) and put them into a nice graphical image. Agree?

**Comment by gyachdav** [comment]
Great Togi hope the exams went well!

so can you translate the two charts that are already there to d3 or google charts? We don't want a static images.

Can you also create a bar chart for the data in https://docs.google.com/spreadsheets/d/1B8F6juFi9qfN_ma3SscCpYSeHqFxv7wh1HUKXQ3fmNM/edit#gid=1993721615 

(tab 1 char-loc)

Stay tuned will send more data to chart tomorrow.

**Comment by togiberlin** [comment]
@gyachdav Ok, translating [them](https://docs.google.com/document/d/17VFx2gogagzMGQy1BOFpffUVfvSo8fHejDl2pNKMfvA/edit?ts=5707bc94) to Google Charts.

**Comment by gyachdav** [comment]
@togiberlin how can I reach you? skype? gitter?

**Comment by togiberlin** [comment]
@gyachdav my skype is: iam[underscore]togi
For urgent stuff I can give you my WhatsApp, if needed.

**Comment by gyachdav** [comment]
sent you a skype request. I'm gmghome2

**Comment by gyachdav** [comment]
@marcusnovotny @jorjo1 says he cannot find the content of the landing pages you created so far. can you push those into the static folder in the develop branch?

**Comment by marcusnovotny** [comment]
Opened pull request #329

**Comment by gyachdav** [comment]
thanks for the quick action!

**Comment by marcusnovotny** [comment]
Added Daenerys Targaryen Landing Page #365 @gyachdav

**Comment by gyachdav** [comment]
@marcusnovotny no end in sight for stats page. I will only get to Ramsay vs. Reek on Monday.

**Comment by gyachdav** [comment]
@marcusnovotny  send link to Deaenerys file plz

**Comment by marcusnovotny** [comment]
So we'll add things post release?

@gyachdav 
https://github.com/Rostlab/JS16_ProjectF/blob/LandingPages/static/daenerys%20targaryen.md

If I don't get a job offer from Buzzfeed anytime soon I'm going to be seriously disappointed

**Comment by gyachdav** [comment]
yup probably. setting bad example i know..

**Comment by marcusnovotny** [comment]
Expect no blame from me, I wanted to have this done a week ago :no_mouth:

**Comment by togiberlin** [comment]
@marcusnovotny --> just FYI: Statistical visualizations are being uploaded/edited [here](https://github.com/Rostlab/JS16_ProjectA/tree/master/misc/statistics).

**Comment by gyachdav** [comment]
hmm have you checked our predictions lately? https://got-stats.herokuapp.com/characters/Daenerys%20Targaryen

she's at 95% 
not really a winning horse according to us

**Comment by gyachdav** [comment]
@togiberlin we need to improve the treemap. please make sure that the tooltips show numbers, right now they're not really informative. Also is there a chance of placing big blocks close to smaller blocks? or does it all have to go in size order?

**Comment by marcusnovotny** [comment]
It makes sense from the algorithm's point of view, since all her family is dead and the Valyrian people tend to die sooner than others, but most other sources consider her a strong contestant. I think with the dragons her survival is pretty much guaranteed, but of course the algorithm can't take details like that into account.

How do we handle this? I could add a paragraph of her being in danger due to her family's history, that our plod algorithm is really pessimistic and her plotline will therefore continue to be suspenseful in season 6.

**Comment by gyachdav** [comment]
yup make up shit like that, its good :laughing:

**Comment by togiberlin** [comment]
@gyachdav Tooltips are no problem. Now it's 1 AM, I'll go to sleep an continue tomorrow 😴
What I don't like is [visited_locations_per_character.html](https://github.com/Rostlab/JS16_ProjectA/blob/master/misc/statistics/visited_locations_per_character.html), perhaps we can group/aggregate characters into high/medium/low or houses (?)

**Comment by gyachdav** [comment]
just pick up a subset of the top 100 then or something presentable. the long tale is not that interesting anyways.

**Comment by marcusnovotny** [comment]
Added following paragraph

---

##### H3: … Sooo, things are set, right?

Well, almost. In Game of Thrones, there’s always a hint of uncertainty – and you have to admit that a lot of people want to see her dead. [Take this assassination attempt on youtube for example.](https://www.youtube.com/watch?v=MIGYQr6ldJk) We in the got.show editorial department are confident that she’ll end up being victorious, even though our machine learning algorithm is a lot less optimistic. The algorithm mostly takes family history into account, and since her’s was cleared off the map, her calculated likelihood of death is pretty high. See our latest prediction here:

> Placeholder, Daenerys Targaryen PLOD
> 
> Alt text: Daenery’s calculated percentage likelihood of death

No reason to be worried, though. Valar morghulis, remember?

**Comment by goldbergtatyana** [comment]
Wiping tears from laughing @marcusnovotny  :joy: 

Amazing job on Dayenerys landing page! As always!

**Comment by togiberlin** [comment]
@marcusnovotny [Hey Marcus, can you look at this and tell me, if you can integrate it into your Placeholder 1 section of Jon Snow PLOD?](https://github.com/Rostlab/JS16_ProjectA/tree/master/misc/statistics/jon_snow)

**Comment by gyachdav** [comment]
@mammuth @jorjo1 @yashha @mina-zaki @Andrew094 

Who will now:
- convert the landing pages that @marcusnovotny  created into html?
- add missing screen shots as per @marcusnovotny instructions in the page?
- include the first paragraph of the landing page in the start page?
- integrate the page into the site (i.e. arrange the routes to load the page). 
- test

**Comment by marcusnovotny** [comment]
@togiberlin Looks nice, that's part of Project F's scope though. Delegating the question :wink: 

Please no screenshots for the tool placeholders, implement the real stuff! We want to show off don't we :grin:

**Comment by gyachdav** [comment]
I agreed to static images in the interest of time, but yes @togiberlin pleas include the original and not low quality screenshots.

**Comment by togiberlin** [comment]
@marcusnovotny @gyachdav Everything I did is not static , it's all Google Charts / JS

**Comment by yashha** [comment]
I started working on them

**Comment by mammuth** [comment]
The landing-pages we have translated until now have been merged:
- Daenerys
- Jon Snow
- House Stark

It makes sense to just add PR's for the next markdown files we get.

**Comment by yashha** [comment]
But only Jon Snow is presentable, the others need design adjustments

**Comment by mammuth** [comment]
Then the question is, why I should merge it. :wink: 
Nevertheless: Should we remove the other two from the sitemap as long as they're not ready?

**Comment by yashha** [comment]
I don't think this is neccesary
Do you think people find the pages on Google?

**Comment by mammuth** [comment]
> Do you think people find the pages on Google?     

Well, that's why we did those landingpages, right? :relaxed: 

However it'd surprise me, if any of our pages would be on the first pages of search results within the next months when searching for "meaningful" queries :wink:

**Comment by gyachdav** [comment]
@togiberlin please use better color scheme so we can see the charts in the landing pages. see example charts and styles here https://got.show/statistics

**Comment by togiberlin** [comment]
@yashha Can you copy the statistics over again? [Jon Snow Statistics](https://github.com/Rostlab/JS16_ProjectA/blob/master/misc/statistics/jon_snow/jon_snow_infographic.html) @gyachdav

**Comment by yashha** [comment]
If you have now changes to the landing pages, just change the html files and make a pr :)

**Comment by gyachdav** [comment]
@yashha if we now edit the HTML wont those edit be overwritten the next time you parse MD->html?

**Comment by marcusnovotny** [comment]
Added Lannister Landing Page #414 

File link: https://github.com/Rostlab/JS16_ProjectF/blob/LandingPages/static/house-lannister.md

It's dooooone. 'Twas a blast!

**Comment by boriside** [comment]
@gyachdav should we add background epic music to the portal?

**Comment by sacdallago** [comment]
Oh god. No! :D @boriside I hate pages that start music in the background

**Comment by AlexMoroz** [comment]
@boriside never use autoplay attribute, it's like goto, just forget that it exists ))

**Comment by boriside** [comment]
@AlexMoroz @sacdallago 

 :D ok you convinced me

btw check the marketing:
![eaef88ae00536e90bf27338f723533ef854ba5a0084fcb0f784919212ffb3ca6](https://cloud.githubusercontent.com/assets/4656678/14493449/d1d749f8-0185-11e6-87fe-89a507600ef6.jpg)

**Comment by sacdallago** [comment]
:D She _might_ be working at the chair... _might_... But still! :D :D

**Comment by marcusnovotny** [comment]
A few issues regarding Daenerys & House Stark Page.
Daenerys:
- In the last paragraph it still says "> Placeholder, Daenerys Targaryen PLOD
  Alt text: Daenery’s calculated percentage likelihood of death" - that should have been replaced with the actual PLOD image and then the alt text for the image

House Stark:
- Images are way too big, completely out of proportion
- Twitter tool picture is taken from the buggy version
- Still a lot of alt text noted as quotations

**Comment by gyachdav** [comment]
Routes to landing pages:
- [ ] https://www.got.show/why-jon-snow-is-not-dead
- [ ] https://got.show/Why-Daenerys-Targaryen-will-win-the-Game-of-Thrones
- [ ] https://got.show/House-Stark-in-Game-of-Thrones
- [ ] https://got.show/When-Theon-Met-Ramsay
- [ ]  https://got.show/Who-will-die-next-House-Lannister

**Comment by sacdallago** [comment]
Mh. What if we think ahead of time and make the routes something like:

https:// got.show / **post** / why-jon.snow-is-not-dead

**Comment by julienschmidt** [comment]
What would be the benefit of that?

**Comment by sacdallago** [comment]
Clarity!
If in the future we want to produce more landing pages, or to provide a blog-like post functionality, we would have an established pattern.

Similar to having characters after the /character/xyz 

If you put it in the root... well.. who knows!

**Comment by marcusnovotny** [comment]
RIght now there's no way to get from the Landing Pages to the Homepage. Could you include the Header on the pages? Then we can actually use them to direct traffic :)
@yashha

**Comment by marcusnovotny** [comment]
The "Enter Page" button is a start but not really inviting. Why not just implement the whole header, so people see immediately that they can look up characters and there's some sort of Map / ranking?

Also, still mistakes in the landing pages (Alt text displayed as regular text, buggy twitter images eg. for Jon Snow...)

**Comment by yashha** [comment]
Closed in favor of #422
