### ISSUE TITLE
Integrate map

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#17]
Map should be integrated
I found it on npm
https://www.npmjs.com/package/rostlab-js16-c10

**Comment by yashha** [comment]
@AlexBeischl 
Not working yet. I don't have an idea, how i can include it.
I have i did import it,
but include doesn't work.

**Comment by sacdallago** [comment]
Also mind that the package name has changed to `gotmap`, https://www.npmjs.com/package/gotmap

**Comment by yashha** [comment]
I think i tried that too, but i'll try it.

**Comment by yashha** [comment]
i did 
`npm install gotmap --save-dev`
and 
`import 'gotmap';`
=>
`ERROR in ./app/main.jsx
Module not found: Error: Cannot resolve module 'gotmap' in /home/yasar/Workspace/web/jsseminar/JS16_ProjectF/app
 @ ./app/main.jsx 26:0-17
`

**Comment by AlexBeischl** [comment]
@AlexMoroz is doing the integration via npm, not me ;)

**Comment by AlexMoroz** [comment]
How are you going to integrate it if we didn't decide about the way to integrate it?
#5  is still open.
What magic did you expect to happen after `import 'gotmap';`?

**Comment by sacdallago** [comment]
:D that you... got.. map? @AlexMoroz  :D :D :D time to push towards integration! If **F** is not expressing preferences, just go for whatever you prefer @AlexMoroz

**Comment by AlexMoroz** [comment]
working on it, trying to bundle all together with webpack

**Comment by AlexMoroz** [comment]
By the way, you can try it now. There is still problems with extraction of html module, but js works correctly.

**Comment by sacdallago** [comment]
I knew I could count on you, I know it would take you much less than 6d.
Please someone from F try this out and report here with questions, concerns, observations ASAP

**Comment by yashha** [comment]
Not working yet (branch map)
http://i67.tinypic.com/287zqit.png
It's not loading the map.

**Comment by AlexMoroz** [comment]
I knew that it cannot be so easy. I will fork the F repo, and check what's the problem.

**Comment by AlexMoroz** [comment]
But first, @yashha try to run it after require. 
Something like this:
`require("gotmap")();`

**Comment by AlexMoroz** [comment]
I've published `gotmap@0.0.13` right now. So it should work without be run.
Just: `require("gotmap");`

**Comment by yashha** [comment]
Awesome, its loading :)

So I need to get the authorization working.
And you should store the images locally I  think.

`Uncaught ReferenceError: episodes is not defined(anonymous function) @ bundle.js?c390:11566fire @ jquery.js?27d9:3182self.fireWith @ jquery.js?27d9:3312jQuery.extend.ready @ jquery.js?27d9:3531completed @ jquery.js?27d9:3547
jquery.js?27d9:9175 
POST https://got-api.bruck.me/api/cities/find 401 (Unauthorized)
GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/labels/0/y0x-1.png 404 (Not Found)
y0x2.png:1 GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/bg/0/y0x2.png 404 (Not Found)
y0x1.png:1 GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/bg/0/y0x1.png 404 (Not Found)
y0x-1.png:1 GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/bg/0/y0x-1.png 404 (Not Found)
y0x2.png:1 GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/labels/0/y0x2.png 404 (Not Found)
y0x1.png:1 GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/labels/0/y0x1.png 404 (Not Found)`

**Comment by yashha** [comment]
I don't like that the map stops you from scrolling down, not a that great ux and the person will probably never see the beautiful footer.

**Comment by AlexMoroz** [comment]
Group 10 will fix the authorisation. 
About the images, they weight 400 mb and there is no possibility to publish them to npm.
We decided to use them from repo. But we need to think about it.

**Comment by AlexMoroz** [comment]
> I don't like that the map stops you from scrolling down, not a that great ux and the person will probably never see the beautiful footer.

Open the issue in project C10 :D

**Comment by yashha** [comment]
You can leave to images on git hub, but thery have to be accessible
`https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/bg/0/y0x2.png 404 (Not Found) y0x1.png:1 GET`

The ux issue should be discussed in here.

**Comment by AlexMoroz** [comment]
If UX issue needs answers from project C10, you have to discuss it there.

**Comment by sacdallago** [comment]
@AlexMoroz  remember that everything config related, for example now that C10 needs:
1. The location of the API
2. The Token setting

needs to be made available for setup when requiring the project. Something like:

```
var component = require('component');
component.config({
    apiLocation: "something.com/something:port"
    apiToken: "Token"
})
```

P.S.: Sorry @AlexBeischl , meant to notify @AlexMoroz

**Comment by AlexMoroz** [comment]
I think this message was for me) Ok, I will add it

**Comment by AlexMoroz** [comment]
Does it work now, after init function added?
https://github.com/Rostlab/JS16_ProjectC_Group10/commit/a74a73c231ee62675b4b4397b1610561c37fda2a

**Comment by yashha** [comment]
Sry for late feedback, no it doesn't work it don't even include some js I think

**Comment by yashha** [comment]
Ok moment I didn't follow your link

**Comment by yashha** [comment]
@AlexBeischl Where I get the the key and the location from?

**Comment by AlexMoroz** [comment]
Project A, but it should work without it now
just run 

```
var map = require("gotmap")
map.init();
```

Config is not implemented in C10 yet

**Comment by yashha** [comment]
Still no characters, but the map is loading and the cities are shown :+1:

**Comment by AlexMoroz** [comment]
Are there some errors except missing map parts?

**Comment by AlexMoroz** [comment]
Did you add jquery and bootstrap(js & css)?

**Comment by yashha** [comment]
`Uncaught ReferenceError: realm is not defined`
I think its caused by you :)

**Comment by AlexMoroz** [comment]
oh, nobody merged my pull request =(

**Comment by AlexMoroz** [comment]
gotmap@0.0.23 was published
check again now please

**Comment by yashha** [comment]
`Uncaught ReferenceError: realm is not defined`
`XHR finished loading: GET "https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/data/cities.js".`
`XHR finished loading: GET "http://localhost:8080/sockjs-node/info?t=1458253163869".`

**Comment by AlexMoroz** [comment]
> Uncaught ReferenceError: realm is not defined

still? did you download a new version?

> XHR finished loading: GET "https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/data/cities.js".

WHAAAAAT?

ok, will look at this tomorrow

**Comment by yashha** [comment]
The XHR are no errors, just the realm error is there

**Comment by AlexBeischl** [comment]
If you want, we  (@mbandle @tPiffrader & myself) can have a skype meeting with you tomorrow, to answer some of your questions regarding the integration of our map

**Comment by yashha** [comment]
I have time
Do you have already a time?

**Comment by bandle** [comment]
Do you have any suggestions? As long as not before 10am its fine :)

**Comment by yashha** [comment]
maybe 10am :D

**Comment by jorjo1** [comment]
It works for me at anytime also not earlier than 10am (_pls_). So 10 or 10:30 will do. Vote!

**Comment by AlexBeischl** [comment]
I can't join the meeting earlier than 11:30, because I have a appointment.

Therefore I would suggest we can start at this time.

**Comment by jorjo1** [comment]
12 o'clock it is then

**Comment by bandle** [comment]
how are you called on Skype? I'm maxiban

**Comment by bandle** [comment]
@yashha 
Focussing the zoom on characters works now
 `map.focusOnCharacter(id)`
and the map will zoom In. This is automatically performed when adding a new character.

Also we added the 2 helpers `showAllCharacters` and `hideAllCharacters`

**Comment by AlexMoroz** [comment]
Integrated.

main.jsx

```
import map from "gotmap";
map.init();
map.demo();
```

MapComp.jsx

```
export default class MapComp extends Component {
  render() {
    return (
      <div className="map-wrapper">
        <div id="map">
        </div>
        <div id="sidebar">
          <form id="filter">
            <div className="input-group">
              <input type="text" className="form-control" placeholder="Search for..."></input>
              <i className="glyphicon glyphicon-search form-control-feedback"></i>
            </div>
          </form>
        <hr />
        <div id="characters"></div>
        </div>
        <div id="timeline"></div>
      </div>
    );
  }
}
```

@yashha 
![screen shot 2016-03-19 at 19 24 20](https://cloud.githubusercontent.com/assets/5850187/13900603/4fd010d6-ee0a-11e5-9ace-b48d9f2ce00d.png)

**Comment by AlexMoroz** [comment]
It has slider error, but it works fine, I've already ask C10 about slider.
And time line doesn't appears. But it's not an integration problem.

**Comment by AlexMoroz** [comment]
@yashha 

fix for the timeline:
add jquery-ui package 

```
import "jquery-ui";
import map from "gotmap";
map.init();
map.demo();
```

**Comment by AlexMoroz** [comment]
`gotmap@0.1.0` published, should work now

**Comment by bandle** [comment]
Docs for our API  are online:
https://github.com/Rostlab/JS16_ProjectC_Group10/wiki

**Comment by mammuth** [comment]
The map is really sexy guys! 
You did an **absolutely great job** on that! :heart_eyes:

**Comment by bandle** [comment]
Map looks good on your page :+1: 

@yashha 
What do you think about changing the CSS property `height` in .gotmap-dropdown to `max-height` 

This would fix this minor issue
![bildschirmfoto 2016-03-20 um 23 40 21](https://cloud.githubusercontent.com/assets/11232638/13907717/204900f2-eef5-11e5-9398-2c02a70dd1df.png)

**Comment by yashha** [comment]
Thanks @mbandle
