### ISSUE TITLE
Heroku demo site title change

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#171]
GOT Stats -> A Song Of Ice and Data

**Comment by mammuth** [comment]
IMHO this doesn't make any sense - most people bookmarked / remembered the old url and after the initial deploy on got.show the heroku app won't be used by anoone else than the devs.

**Comment by jorjo1** [comment]
The page title was meant here! :D

**Comment by yashha** [comment]
Ah :D

**Comment by mammuth** [comment]
Then this is closed in https://github.com/Rostlab/JS16_ProjectF/commit/3f14bf61eea43f9ee09ade425286b1324f32225c

**Comment by yashha** [comment]
oh ok :D
