### ISSUE TITLE
Sorting options

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#174]
The options should be 
Popularity
A to Z
Z to A

**Comment by mammuth** [comment]
If you mean "Name desc" should be named "Name Z to A" then this is closed in https://github.com/Rostlab/JS16_ProjectF/commit/68d1a5cd7a829a74a868b414bef5208a58964df5. 

If not then the new final Sorting options are:
_Most popular (book) (default)_
Name A - Z
Name Z - A
Most liked (Twitter)
Most hated (Twitter)
Survival chance (comment: this is 100 - death_chance)
Death chance 

As discussed in the meeting with the tutors today, those are the new sorting-options, the character-listing should be sorted by. @Andrew094 can we assign this one to you?

**Comment by gyachdav** [comment]
#33

**Comment by mina-kleid** [comment]
#182
