### ISSUE TITLE
Antagonists for homepage

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#176]
From our meeting:
_Rotation-Content:_
_2 characters (Arya vs Cersei, find out who are the main antagonists) have stats as on a ranking page (PLOD (with explanation), Sentiments) and one map under opposite images._

Please provide a list of antagonists we should display @sacdallago. We're not that into the show that we will find good ones :wink:

**Comment by sacdallago** [comment]
:D Neither am I. Never seen one episode, never read a book :D I think I am possibly the worst person to assign this to :laughing: 

Assigned @gyachdav but he can delegate

**Comment by mammuth** [comment]
Since obviously all the listing and discussion went into the implementation issue, I'm gonna close this one.
