### ISSUE TITLE
Homepage antagonists implementation

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#177]
_Rotation-Content:_
_2 characters (Arya vs Cersei, find out who are the main antagonists) have stats as on a ranking page (PLOD (with explanation), Sentiments) and one map under opposite images._

~~Take the list of #176.~~
Maybe fill their infos / image-link into a json file, so it'd be easy to change characters?

**Comment by gyachdav** [comment]
@AlexBeischl @marcusnovotny  please help me out here. This is a list of possible interesting face offs:

Arya Stark vs Cersey Lannister 
Ramsay Snow vs Sansa Stark
Stannis Baratheon vs. Joffrey Baratheon
Gregor Clegane vs. Oberyn Marttel
Jon Snow vs Ygritte
Theon Greyjoy vs Ramsey Snow
Ilyn Payne vs Bronn
Tryion Lannister vs Petyr Baelish 
Mellisandre vs Davos Seawoth
Cersey Lannister vs. Margery Tyrell
Robert Baratheon vs Rhaegar Targeryan
Eddard Stark vs Tywin Lannister
Jaime Lannister vs Aerys Targaryen
Jaime Lannister vs Robb Stark
Catelyn Stark vs Walder Frey
Daenerys Targaryen vs Tyrion Lannister 
Daenerys Targaryen vs Euron Greyjoy
Aeron Greyjoy vs Euron Greyjoy
Brandon Stark vs Brynden Rivers
Dunk vs Aerion Targaryen

**Comment by AlexBeischl** [comment]
Well the only addition coming to my mind:
Tyrion vs Jaime (next meeting, as Jaime is thinking about killing him)

**Comment by marcusnovotny** [comment]
You missed one

> Petyr Baelish vs Everyone

In all seriousness: @gyachdav provided an impressing list of combinations already which contains all the characters I can come up with on the fly. Some more ideas after googling GoT main characters
- Brienne of Tarth & Sandor Clegane (The Hound)
- Arya Stark & A Man (nameless assassin)
- Petyr Baelish & Lord Varys
- Jorah Mormont & Daenerys Targaryen
- Cersei Lannyster & The High Sparrow
- Mance Rayder & Jon Snow
- Bowen Marsh & Jon Snow

The only thing I could come up with initially were different combinations of those characters, like Eddard Stark vs Joffrey Baratheon or Jaime vs Cersei Lannister. I mean it doesn't even have to be antagonists, I thought it was just as interesting to see who's the more popular sibling.

... Which makes me think: Wouldn't it be amazing to include an option where visitors can select their pair themselves? Much more exciting than just being served random pairs I think!

Totally loving this idea by the way. That's definitely the coolest use case for our stats. Only one sidenote: Be sure to exclude PLOD for dead characters to not embarass our algorithm, just in case there's some zombies :ghost:

**Comment by sacdallago** [comment]
This is already a good enough list.
Thanks all guy(s) :D You can implement this now

**Comment by yashha** [comment]
How is this?
We could make a link to wikipedia in the right bottom of a image.
Or should it be stored locally?
http://pastebin.com/hWiBdgsh

**Comment by yashha** [comment]
I think we go without additional images.

I summed the suggestions up.
http://pastebin.com/Qs9PCJYH

**Comment by yashha** [comment]
Branch https://github.com/Rostlab/JS16_ProjectF/tree/antagonists
Feel free to work on it

**Comment by mammuth** [comment]
WIP-PR: https://github.com/Rostlab/JS16_ProjectF/pull/236

**Comment by jorjo1** [comment]
I think we can close this one and go further, but in design: #310

**Comment by gyachdav** [comment]
I want to add/modify the list of antagonists. which file should i edit?

**Comment by yashha** [comment]
https://github.com/Rostlab/JS16_ProjectF/blob/develop/app/components/common/AntagonistsComp/antagonists.json
