### ISSUE TITLE
Character sorting

### ISSUE THREAD

**Issue by mina-kleid** [Rostlab/JS16_ProjectF#182]
From from latest discussion, character sorting should include twitter sentiments, plod, name, books.

The problem is there is no one place that provides all of this, we get basic character details from A, plod from a different request to A, and twitter sentiments from D4. 
Its hard to sort on this scattered character data. One suggestion is to keep it simple for the first release and just sort on the basic character details we get from getting all character list from A, and marking the rest as a nice to have for later.

**Comment by sacdallago** [comment]
You have a back-end now, right?
How about: You cache the chars you get from A, which is what you do anyway if I'm not mistaken, and simply store in the cache also some data like the PLOD and sentiment for the character. just for the sorting side. Sure, the data, especially the sentiment one, is not gonna be SUPER up to date, but if the cache has a 24h TTL, then you have a good enough aproximation

**Comment by mina-kleid** [comment]
@sacdallago that means extra work and moving the sorting we have already implemented on client side to the backend and reimplementing it with merging and caching. Thats why add these extra sorting as a nice to have since we dont have the time on our side

**Comment by sacdallago** [comment]
Good, this _could_ be done between FF and deadline.
My estimate is 2h work-work.
But do as you see fit!

**Comment by mammuth** [comment]
#280
