### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#188]
This is a very important question.
If we can't use the images from HBO, which image we are going to use for the website?
Especially regarding the homepage #177 we NEED images.
@gyachdav @sacdallago and members of project F

**Comment by gyachdav** [comment]
why not use the images we already have from the awoiaf wiki?

**Comment by gyachdav** [comment]
@theocheslerean  @boriside:  if anyone is up for the challenge, then wikipedia shows images from the show that can be scraped and used under the fair-use license 

e.g. 
https://en.wikipedia.org/wiki/Brienne_of_Tarth
https://en.wikipedia.org/wiki/Joffrey_Baratheon

If anything I would recommend only trying characters that have been in show epsiodes

**Comment by yashha** [comment]
Ok, lets do this.
We still have to get rid of the big image on the landing page and have to replace it.

**Comment by sacdallago** [comment]
Isn't that CC0? :D :D :D I was using that one as if it was CC0. Life is full of surprises :laughing:

**Comment by yashha** [comment]
We have you read it is CC0 :O ^^

**Comment by jorjo1** [comment]
I say we make a picture of the initial letters of a characters name Forever Example -> FE, just in case we don't find some photos. I think we will have to deal with using awoiaf pictures and forget about them being ugly.

**Comment by yashha** [comment]
So no fair use?

**Comment by yashha** [comment]
I think you are right. @jorjo1

**Comment by gyachdav** [comment]
So are we scraping images from wikipedia? We're allowed to use them.

**Comment by sacdallago** [comment]
Yes. Everything Wiki-related is under CC

**Comment by yashha** [comment]
The text yes, but the images can be non-free but wiki use them under fair-use terms.
That's what I read.
https://en.wikipedia.org/wiki/File:Jon_Snow-Kit_Harington.jpg

**Comment by gyachdav** [comment]
Fair-use allows us to reuse those images. It's kind of murky but let us get away with murder.

**Comment by sacdallago** [comment]
Or commons.wikimedia.org , but on a quick search nothing relevant popped up for me
