### ISSUE TITLE
Link to the API and contributions

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#189]
Please put two links in the footer:
- To the API docs: api.got.show (will redirect)
- To contribute: contribute.got.show (will also redirect, for now to rostlab org on github)

Thx

**Comment by sacdallago** [comment]
P.S.: stay tuned, I'm setting up the API on my side and kordian is gonna tear down his, sooo... Time someone asks me about the token :D

**Comment by gyachdav** [comment]
@sacdallago we plan to have a Developers section. Is this in addition to that dev section?

**Comment by sacdallago** [comment]
Yes. This is simply a link on the footer called "contribute" that redirects directly to where the repos are (maybe a different, dedicated org in the future)
