### ISSUE TITLE
Search bar in character page + images + back

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#199]
Hi, I encountered three problems on the staging site (v0.0.8) right now:
1. If I navigate from characters to page three, I get the link https://got-stats.herokuapp.com/characters/?search=&page=3&sort=pageRank&order=-1
   If I open the link directly though, I'm not on the same page 
   ![screen shot 2016-03-30 at 11 57 25 am](https://cloud.githubusercontent.com/assets/6240943/14138636/9a75d3ca-f66e-11e5-84eb-1b0e0653e72a.png)
2. If I search something though the search bar... Well, just try it! :D It's the weirdest thing ever seen
3. Put some placeholder? Everywhere? If I open up a character's page, and then I open up another characters page, until the page loads I get the info of the char before.. Which is very confusing.

**Comment by yashha** [comment]
I didn't you have this jorjo, can I have this?
I have already a patch. @jorjo1
