### ISSUE TITLE
Footer Fix Mobile Design

### ISSUE THREAD

**Issue by Andrew094** [Rostlab/JS16_ProjectF#20]
Markup and design of the footer

**Comment by mammuth** [comment]
Related to #18

**Comment by Andrew094** [comment]
The Mockup psd doesn't have a footer section, so someone still has to come up with one

**Comment by mammuth** [comment]
Subtask of #37

**Comment by sacdallago** [comment]
@Andrew094 best habit is that **someone** becomes a specific person! :) You can always ask your team mates by mentioning them, worst case they are gonna set your car on fire and kill your favorite stuffed animal in his sleep, com'on: it was time to grow apart from it anyway, wasn't it? (I'm totally not talking out of personal experience like, I watch [serious](https://www.youtube.com/watch?v=DOBg9qG5wpw) shows and stuff)

**Comment by mammuth** [comment]
@Andrew094 I just noticed you already did some work 2 days ago :flushed:

I like your footer implementation! Are you going to rebase it to the current develop branch and open a PR?

**Comment by jorjo1** [comment]
Come on! 
**Somebody** has to do this. Just do a pull request so we can put it right in place. Otherwise the task will be assigned to somebody else. :see_no_evil: :sweat:

**Comment by Andrew094** [comment]
Yes, I am looking at it right now

**Comment by yashha** [comment]
@Andrew094 Looks really good on desktop, but [mobile](http://tinypic.com/r/29fpag0/9) ;)
