### ISSUE TITLE
Project D Visualization: Hangout with Groups 4 & 5

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectF#200]
Hey there!

Our Project D groups 4 & 5 were having a vivid discussion about our visualization [here](https://github.com/Rostlab/JS16_ProjectD_Group5/issues/73#issue) and need some input from you guys. It would be best if we could have a Hangout today with the relevant contact from your Project. I'd propose 7 PM, but I don't mind any other time, will be working on this all day.

**Group D4** provides a visualization of the daily (hourly) twitter sentiment scores over the past 5 years in a pannable / zoomable graph. This is the status quo:

![](http://i.imgur.com/tTwkR3Q.png)

In the screenshot, you can only see the data for part of season 4. From there you can zoom out to view 2011-2016 or in to view specific weeks / days.

**Open questions Group D4**
- Where will you display the graph / how do you intend to use it?
  - Do we have to add a menu / navigation or will you serve only the graph (preferred from my part)
- Can you give us some visualization guidelines regarding colors, fonts etc. so we'll match the site theme
- What size do you need the graph in? Does it have to be resizable? It currently features set height of 480 px & resizable width that maxes to window size.

@kajo404 @jonny3576 Please add your questions so Group F can prepare :)

**Comment by yashha** [comment]
Looks good already!
I'll be there :)

**Comment by jcebel** [comment]
@Logarythms @vanp33 This could  be  also interesting for you :) 
Well my question is, what will Project F do with the stats from D5? How will they visualize it and what do they think of the pop-up-box idea?

I'll be there, too!

**Comment by mammuth** [comment]
Maybe it's a good idea to directly add a legend to your graph?

**Comment by jcebel** [comment]
@marcusnovotny I am ready.. Are you creating a group?

**Comment by marcusnovotny** [comment]
@mammuth @jonny3576 @yashha 
[Join me on Hangouts](https://hangouts.google.com/call/4hy2nfzn5rbqxayofgl3qvimrqe)

**Comment by marcusnovotny** [comment]
We're done already. @yashha & I talked, @jonny3576 joined but we couldn't hear him so he was only listening (Hangouts issue).

**Regarding our questions**
- No menu needed from D4, but we'll create a Legend
- Dynamic resizing in one dimension (width) is okay, height can be easily specified for the containing svg element.

We'll stay in touch in case anything new pops up.

**Comment by kajo404** [comment]
I heard there are still some unresolved issues regarding group 5. If so please let me know and we can skype / hangout tomorrow morning to get everything solved :)
