### ISSUE TITLE
/map initial zoom 

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#207]
We should fix the map initial zoom because it seems to me a bit awkward to have blue fields around the map. This is my idea and I would like to have a bigger initial zoom like here: http://gameofthrones.com/game-of-thrones/season-5/episode-10/map/location/5/braavos-free-city

@mbandle @AlexBeischl 
How can we fix this on our side? Thanks!

**Comment by jorjo1** [comment]
I just found a glitch. Is the problem solvable?
![image](https://cloud.githubusercontent.com/assets/2246472/14180426/31bdb078-f763-11e5-8c27-18f21918c686.png)

**Comment by gyachdav** [comment]
@mbandle @AlexBeischl @tPiffrader can you please help @jorjo1 fix?

**Comment by bandle** [comment]
@sacdallago can you replace the defect tile by refreshing your tiles.got.show site:

Or just replace this one - its the only bad one

https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/tiles/labels/5/y14x20.png

**Comment by sacdallago** [comment]
I'll pull the last `gh-page` branch and copy the content of tiles from there to the location that tiles.got.show services. Will that do?

**Comment by bandle** [comment]
Yes this will do - we published the fix some days ago

**Comment by bandle** [comment]
We set our initial zoom to display the whole got world. But you can change it by setting the zoom manually. 
Just get the leaflet object: https://github.com/Rostlab/JS16_ProjectC_Group10/wiki/Using-the-API#internals
And then call zoomIn : http://leafletjs.com/reference.html#map-zoomin

**Comment by sacdallago** [comment]
1. The copying should be done from my side, can you check?
2. map.got.show is at the latest version

**Comment by bandle** [comment]
Works :+1: 

![bildschirmfoto 2016-04-02 um 15 55 22](https://cloud.githubusercontent.com/assets/11232638/14226741/59629a74-f8eb-11e5-83bb-0dd50288af2b.png)

**Comment by gyachdav** [comment]
Currently the map is still way too zoomed out on the map page. Also the map is not centered in the middle of the page but seems to be placed a bit to the right. please center the map and zoom in.

**Comment by jorjo1** [comment]
@mbandle is it only me, or the cities are shown on the map after I zoom in/out? How can I handle this? Thank you.
