### ISSUE TITLE
Spoiler alert

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#210]
Should we indicate somehow that there are spoilers on the page? For example a warning in some corner of the page or a popup? Yes, we know that the page contains spoilers, but we speak of DAU (dumbest user)..

**Comment by sacdallago** [comment]
Nah. One knows where he/she is getting himself/herself into.

**Comment by jorjo1** [comment]
I can not agree, for example gameofthrones.com has a message that there are
spoilers. :see_no_evil:

**Comment by sacdallago** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Game_of_Thrones) doesn't :D 
I hate messages in general on pages, they always sound like [ads](https://www.youtube.com/watch?v=z696bTiP8Ro).
This makes me think of a new issue for you :dancer:
