### ISSUE TITLE
Statistics page

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#216]
How many females/males
Average age of males/females
Most popular name/ least popular name
The longest traveller (by distance)
Character travelled the least

**Comment by gyachdav** [comment]
[ideas draft ](https://docs.google.com/document/d/17VFx2gogagzMGQy1BOFpffUVfvSo8fHejDl2pNKMfvA/edit)

**Comment by jorjo1** [comment]
This should be hardcoded, right? We have no time and no man power to implement those cool features :person_frowning:

**Comment by gyachdav** [comment]
im on it (that's why i'm the assignee :wink: ).

Just consider this as you would consider any other landing page. make sure you route to it and that you pull the contents from the static folder. The rest is on me.

**Comment by gyachdav** [comment]
@goldbergtatyana @togiberlin  I think i got the first installment of the statics page. it will talk about characters and their survival rates and it will show the data and charts that @goldbergtatyana created.
The other ideas we talked about and the data we collected will go into other statistics page that we will release later (like landing pages).
please take a look at https://docs.google.com/document/d/1S2053Bkf97sJ-Szlho0xHTDVX98f6WNTb_VJl6zEi8E/edit#

this is a first draft of the content that will go into this stat page. 

@togiberlin  please make sure that all charts in that page exist as google charts. also make sure that he color scheme for the charts fits the website color scheme. 

@goldbergtatyana thanks a lot for making this happen!

**Comment by sacdallago** [comment]
Why is it everyone is always protecting their files :(

**Comment by gyachdav** [comment]
Just uploaded the final version of the first stats page. please:
- [x] check it doesn't break anything
- [x] load content into the statistics section
- [x] put first paragraph in the start page
