### ISSUE TITLE
Implement get plod for character

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#219]
The API has a call for getting the plod for a certain character:
https://api.got.show/doc/#api-CharacterPlod

we need this to use in our character-detail page.

Related: #178

**Comment by mammuth** [comment]
Btw, somehow there should be two predictions - we should use the one of Group 6 as the main prediction, @goldbergtatyana said.

**Comment by mina-kleid** [comment]
@mammuth isnt this solved by this ? https://github.com/Rostlab/JS16_ProjectA/issues/101

**Comment by sacdallago** [comment]
Yeah, just need to figure out once you actually can GET the data, which one has the right `desciption` attribute and just take those PLODS as the primary ones

**Comment by mammuth** [comment]
@mina-zaki 
I'm not quite sure how you think the linked issue solves this. 
I was suggesting that we could add this api call to our server component, or maybe to the character-object itself, so we can easily query the plod in the character-detail-page or the 1vs1 comparison on the homepage (#117).

**Comment by mina-kleid** [comment]
Yea it was my bad, i thought the PLOD comes with the character. but it doesnt. will find a way to solve it and add it to the character

**Comment by mammuth** [comment]
Correct!
It used to be that way, but in your linked issue there is the discussion why it's moved out of the character-response I think.

**Comment by gyachdav** [comment]
@mina-zaki you can also ask project A how to get it. @kordianbruck?

**Comment by sacdallago** [comment]
@mina-zaki while we are [**waiting** for **A** to wake from the sleep](http://3.bp.blogspot.com/-Mz57qH8WorI/VYd-KmxVnhI/AAAAAAAAAGI/uxewXVWsKNU/s1600/WAKE-UP-SLEEPING-BEAUTY-GAME.png) you can get the PLODs directly by importing the two packages from the **B** groups ([1](https://www.npmjs.com/package/gotplod) and [2](https://www.npmjs.com/package/gotarffplod)) and querying the PLODs by character name
