### ISSUE TITLE
Sitemap Generator

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#221]
We need a react sitemap generator for all pages.
- All basic pages: Home, Map, Ranking, Characters, About, ...
- All 2000 character-detail pages
- All Landing-Pages (with high priority)

Future-Feature:
Prioritize character-detail-pages based on the characters popularity.

**Comment by mammuth** [comment]
Assigning to @Andrew094 since he already did some work on the sitemaps.

**Comment by Andrew094** [comment]
@mammuth I was just testing one static sitemap, but I have no idea how to do this dynamically with a generator.

**Comment by mammuth** [comment]
Nor do I. :wink:

But since the sitemap won't change a lot, we could build it with a standalone script aswell. 

Get all characters by the api, urlencode their names, make them to the format of our pages and the sitemap. We could even bring up a way to set the priority based on the characters pagerank.

**Comment by gyachdav** [comment]
Also cannot wait here forever. Reassigning to @mammuth
