### ISSUE TITLE
React is insecure move entire website to angular

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#223]
just read this https://facebook.github.io/react/tips/dangerously-set-inner-html.html

**we need to move to angular 2 asap**

@jorjo1 @yashha @mina-zaki @Andrew094 @sacdallago

**Comment by sacdallago** [comment]
could you put anymore labels @gyachdav ? :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: 

This is quite a :bomb:

**Comment by yashha** [comment]
We don't even use dangerouslySetInnerHTML ;) (yet)
So keep calm :)

**Comment by mina-kleid** [comment]
April's fool for sure :smile:

**Comment by gyachdav** [comment]
![](http://i.imgur.com/QJrcNQc.jpg)

**Comment by jorjo1** [comment]
This one got me

**Comment by mammuth** [comment]
My reaction when receiving the mail:
![swagger-stunned-o](https://cloud.githubusercontent.com/assets/3121306/14208792/66c65cf2-f821-11e5-8e2e-da5ee10cad70.gif)

**Comment by sacdallago** [comment]
He also kinda looks like you @mammuth :open_mouth:

**Comment by jorjo1** [comment]
There was no REACTion I could make us of!
