### ISSUE TITLE
Website sections

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#227]
Here is the list of sections that should be at the navigation bar:
- [x] Characters - https://github.com/Rostlab/JS16_ProjectF/issues/33
- [x] Rankings - https://github.com/Rostlab/JS16_ProjectF/issues/40
- [x] Map - https://github.com/Rostlab/JS16_ProjectF/issues/207
- [x] Statistics - https://github.com/Rostlab/JS16_ProjectF/issues/216
- [x] Contribute - https://github.com/Rostlab/JS16_ProjectF/issues/189
- [x] About - https://github.com/Rostlab/JS16_ProjectF/issues/234

**Comment by goldbergtatyana** [comment]
<strike> And also 
- [ ] Credits 

page with the list of all contributors. @gyachdav do you agree? </strike>

The JST group picture from the stairs can be found here: https://rostlab.org/~goldberg/JST_Seminar2016.jpg

**Comment by mammuth** [comment]
@yashha I have no problem in doing this, you can leave me assigned; you already did a lot and there are probably some react/configuration heavy issues that suit your experience with our setup.

**Comment by yashha** [comment]
I thought it is about routing and setting up page, which is no problem for me, you should focus on design :D

**Comment by goldbergtatyana** [comment]
Never mind my previous post. I found that Credits will be part of the "About" #119 #19

**Comment by gyachdav** [comment]
yes the link to credits go in the footer
