### ISSUE TITLE
Character Detail Page

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#23]
~~Data-Content:~~
- ~~Character image (A)~~
- ~~Basic informations about the character (A)~~
- ~~2x PLOD in Tabs (for the two groups in B)~~
- ~~Sentiments on twitter (App by Project D) _There are also 2 groups how to handle this?_~~
- ~~Map for the character~~

**Comment by mammuth** [comment]
If you open any issues on other projects to discuss what we're able to integrate in this detail page, could you please mention this issue, so that everyone is able to follow the progress :blush:

**Comment by mammuth** [comment]
### Sections:
- Basic Info
- PLOD
- Sentiments
- Tweets (?)
- Map
- Link to the Wiki
- Floating Right-Sidebar-Navigation (?)

### PLOD-Section:
- Tabs for the 2 predictions
- Timeline **(?)**

### Sentiment-Section:
- 2 tabs
- Love Reactions: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: 
- Hate Reactions: :rage: :rage: 
- Number of tweets

**Comment by sacdallago** [comment]
Love/hate?
Like/Dislike! Apart from the sentiment analysis not being about love and hate but rather like and dislike, the sentiments you mention are very strong. Be careful :)

**Comment by sacdallago** [comment]
Hey, I saw the draft page, looks nice!
a few suggestions:
- add some color for the number in PLOD (red > 60, gray 60 < < 40, green < 40 , or similar) in general, make features like sentiment and PLOD stick out more, that's what differentiates _us_ from everyone else.
- will you also display some graphs on the page? If I don't remember incorrectly one of the twitter groups has implemented an impressive over-time variation in feelings towards a character
- Implement a twitter widget/live feed at the bottom of the page / at the bottom of every page (even the home, with search query `gotshow`) :D you style a widget via the [twitter widget page](https://twitter.com/settings/widgets) and then in every page you just need to make sure you change the search term, aka:

```
<a class="twitter-timeline" href="https://twitter.com/search?q=got" data-widget-id="711494936588390400">Got live feed</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
```

Where you see `got` you change it to your **URL-ENCODED** search term ("Some Name" --> "Some%20Name" or "Some+Name" depending on what twitter wants)

**Comment by mammuth** [comment]
Thx for the feedback, as you said - that's a really rough draft.
- Header-Background: Originally we were planning to add big background images of the character. However, I'm afraid we don't find a lot of good images we can use for that, so another idea was to add the map as a background there with the characters last-known-location.
- We wanted to display character-specific tweets on the char-detail page. 
- Depending on our target-audience adding tweets to every page might be an option too. If users are mostly from Germany/Europe this would be spamming like hell and almost noone would "use" it. :wink: (thx for your snippet - I've opened a dedicated issue for the tweets (#79)).
- Better highlight PLOD and Sentiment analysis :+1:

**Comment by mammuth** [comment]
Main-ToDo:
- [ ] What to do with the big header? 
- [ ] Query actual data
- [x] Highlight PLOD & Sentiment section
- [x] color for the number in PLOD (red > 60, gray 60 < < 40, green < 40 , or similar)
- [x] Show character on the already integrated map

**Comment by jorjo1** [comment]
**The big header**
For now we are displaying only a background picture which is common for every character in the page.

**Query actual data**
We are actually doing this: we display image, name, some other details that are stable on the API. We do [this](http://m.xkcd.com/1658/) now.

**Comment by jorjo1** [comment]
Characters catalog small thumbnails should make the text look nicer.
- [ ] add padding
- [ ] word wrapping via css

![image](https://cloud.githubusercontent.com/assets/2246472/14003556/e1dbec4c-f153-11e5-8264-873e4f4067fc.png)

**Comment by gyachdav** [comment]
General
- [x] Add “Character Not Found” page (route to 404) https://github.com/Rostlab/JS16_ProjectF/issues/213

Infobox
- [x] https://github.com/Rostlab/JS16_ProjectF/issues/175
- [x] Link to wiki in character details-page https://github.com/Rostlab/JS16_ProjectF/issues/214

Likelihood of Death : 
- [x] @goldbergtatyana  will tell which of two predictors should be used as the main prediction model. @goldbergtatyana will also suggest the text to mention the result of the second model as.

Twitter section
- [x]  take all data from D4. D4 will also provide visualization.  
- [x] Take “controversial” measure from D5. 
- [ ] Bar: number of positive tweets and a bar below for the number of negative tweets
- [ ] What do people say now button: that will show what ppl say  from now on?

Map Section
- [x] By default cover the whole timeline
- [x] Render the size to fit the tables above

**Comment by goldbergtatyana** [comment]
Likelihood of Death:

The more accurate prediction method is that of Group 6 --> this is the main predictor to use.

I added text describing:
1. PLODs on characters' pages
2. The main prediction method (that of Group 6) - this text goes on a separate page
3. The less accurate prediction method (that of Group 7) - this text also goes on its own separate page

as notes of plod-descriptoin.md

Feel free to get your hands on the text ;)

**Comment by gyachdav** [comment]
Some ideas for improvements
- [x]  we need a different heading for the page instead of why do machine learning. How about - "how do we predict likelihood of death" or maybe just present this as an FAQ
- [x] The page for the second algo can go in the same page as the first only at the bottom
- [x] why not use a more compelling URL slug then the ambiguous "plod-description2".... how about "machine-learning-algorithm-that-predict-death-in-game-of-thrones-explained"..  may help with SEO
- [x] use the algorithm name in the description. group 6 is gotarffplod group 7: gotplod

:

**Comment by mammuth** [comment]
Did 2. and 3.
@goldbergtatyana you can edit the [markdown-file here](https://github.com/Rostlab/JS16_ProjectF/blob/develop/static/plod-description.md)

**Comment by goldbergtatyana** [comment]
Did 1 and updated the machine learning description text.

Can we please change the font of the main text? Right now it looks like from the 90s :)

**Comment by mammuth** [comment]
I think it should be the one that's used on the hbo got site, like we discussed in the first meeting. 
I will verify it when I'm on the PC again later today.

**Comment by gyachdav** [comment]
- [x] Change “places associated with <character_name> to “Follow <character_name>”
