### ISSUE TITLE
"About got.show" page

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#234]
- [ ] Short text describing what this website is about @gyachdav will provide 
- [ ] Credits section as described in https://github.com/Rostlab/JS16_ProjectF/issues/19
- [ ] Information about sources and licenses (link to attributions)
- [ ] Class wiki page 
- [ ] Rostlab 
- [ ] TUM

**Comment by gyachdav** [comment]
Status?

**Comment by Andrew094** [comment]
can you post your short text here, also do you want links to rostlab / tum ?

**Comment by jorjo1** [comment]
@andrew094 do you have the google docs link? there is a desc.

**Comment by mammuth** [comment]
Details to all pages:
https://docs.google.com/document/d/1TxGVoVNiqhclnwG5pw8-iRYljKpmjEn91FyTw51IyWk/edit

For this about-page:
_Group picture
Mentors
Front end
Machine learning
Map
Twitter
Database
Keep all in separate row so names will be visible At most have 3 names in one row_

**Comment by sacdallago** [comment]
I think this is done?
