### ISSUE TITLE
Nicer link color

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#240]
Hey guys,

please change the link colur, this is unreadable!

![screen shot 2016-04-02 at 3 49 00 pm](https://cloud.githubusercontent.com/assets/6240943/14226719/85e1d49e-f8ea-11e5-9aea-c7c3853e57e3.png)

**Comment by mammuth** [comment]
Öh, that shouldn't be that way. Probably something is overriding it. Will fix it right now :+1:

**Comment by sacdallago** [comment]
I'm not entirely sure I like this combination of colors for the link either...
Gray on gray, dunno.. Can you experiment a bit? Maybe you come up with something nicer @mammuth 

Also: In the about at the bottom:

> Check out our API Reference here.

The link points to bruck's server. Make that link point to wherever the api is pointed at, but instead of /api just /doc

**Comment by mammuth** [comment]
Yep, the color was primary a hotfix :wink: 
We probably need to introduce a new color for this, semantically it should be something comparable to the red, but much lighter so it looks nice on dark backgrounds.
