### ISSUE TITLE
Images cannot be found

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#241]
I don't know if this is on your side, because the tomb image is definitively on your side, but the images are broken.
All of them.

https://got-stats.herokuapp.com/characters/Rhaenys%20Targaryen

[I opened up an issue in **A** as well](https://github.com/Rostlab/JS16_ProjectA/issues/130). Please try to figure out who is responsible.

**Comment by sacdallago** [comment]
Ok. So:
The problem on the API side has been fixed, but the tomb image is still missing!

**Comment by yashha** [comment]
Can this be closed?

**Comment by sacdallago** [comment]
No?

![screen shot 2016-04-02 at 4 48 47 pm](https://cloud.githubusercontent.com/assets/6240943/14226997/cee4d6de-f8f2-11e5-9230-7e7e7d4b6b47.png)

**Comment by yashha** [comment]
Ah sry :)

**Comment by mammuth** [comment]
This is definitely a problem on our site. And it's due to our strange configs - sometimes when running / building, they're referenced correctly, sometimes not. I have no clue what's happening there. 
But @yashha, that's something you will dig into, right?

**Comment by yashha** [comment]
sure :D
Can you tell me the url of the image in the src?
And any errors?

**Comment by mammuth** [comment]
Just check it out, it's on the character component. 

It's something related to the webpack configuration, I guess. 
For example the src-URL is prefixed by an /assets/ folder in the DOM, however the file is stored at this URL without that assets folder (at least this happened to me once. Some builds / npm starts later the issue resolved itself :P)

**Comment by mammuth** [comment]
As a hint:
The problem will be related to the fact, that static files are handled differently in the dev and in the production settings of webpack (is there actually a reason for that? :smirk:). 
In the dev-settings they seem to be stored inside the assets/ directory, and in the production settings not. 

As a side-note: 
IMHO the root of all evil is probably, that we have **separate configs for dev and building, without a shared base-config.** :bomb: 

My experience is, that the most reliable-solution is to have a base-config and in the dev-/production-config you only store settings that are additions to the base for one of the configs. The dev/production config inherit all settings from the base-settings and have the ability to add more settings.
So for example all normal settings are in base, and in the dev-setting you furthermore load eg. a debug-toolbar or whatever.

Right now it seems like our configs are exactly the opposite of the DRY-methodology, which (as we see) can cause a lot of trouble.

However I have no experience how well the described inheritance-pattern could be applied to webpack-configs.
