### ISSUE TITLE
No way to return from 404 page

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#243]
If you get to the awesome 404-page there is no way back. 
Two solutions:
- Don't hide the navbar
- add a "Back to home-page"-button

![black-holes_o_1873393](https://cloud.githubusercontent.com/assets/3121306/14227894/4cc6df84-f907-11e5-9da2-24029681a935.jpg)

**Comment by sacdallago** [comment]
I'd go for number two!

I just like the full page 404 tohohooo much

**Comment by jorjo1** [comment]
I will do it in a funny way, I promise :)
