### ISSUE TITLE
Fix sitemap

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#246]
https://got-stats.herokuapp.com/sitemap.xml
![image](https://cloud.githubusercontent.com/assets/4728786/14228326/e4dfd08c-f911-11e5-93a0-7b8d1ae8648b.png)

**Comment by jorjo1** [comment]
Can we close this one? #312

**Comment by yashha** [comment]
I stage now and test it

**Comment by mammuth** [comment]
Closed via https://github.com/Rostlab/JS16_ProjectF/pull/312/

**Comment by yashha** [comment]
![image](https://cloud.githubusercontent.com/assets/4728786/14399478/63c5b79c-fded-11e5-9a47-7d3bf08052a9.png)

**Comment by yashha** [comment]
nvm its probably because its the wrong url.
gn8 ^^
