### ISSUE TITLE
CSSLint: Ignore background-fallback

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#25]
`warning  Fallback background-color (hex or RGB) should precede RGBA background-color  fallback-colors`
Doh! only needed for <= IE6

**Comment by yashha** [comment]
Quickfix:
`.navbar-inverse { /* csslint allow: fallback-colors */
    background-color: transparent;
    background-color: rgba(0, 0, 0, 0.3);
    border-color: #080808;
}`

**Comment by yashha** [comment]
or 
csslintrc:
`
{ 
 "fallback-colors": false
}
`
