### ISSUE TITLE
empty character infos showing

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#260]
![image](https://cloud.githubusercontent.com/assets/4728786/14231905/070e11fe-f995-11e5-9b36-8da9a2ed73b6.png)

**Comment by mammuth** [comment]
Seems like the API is returning a title object that is empty. :tada:

**Comment by jorjo1** [comment]
This is done, right? @mammuth @yashha

**Comment by mammuth** [comment]
Oh,  yep, that's definitely done :+1:
