### ISSUE TITLE
No errors on errors - deployment

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#272]
Yellou guys!

I'm putting my hands forward and trying to run your code on the production machine. Has anyone of you tried running the package with locally hosted api? If so, what does your config look like?

I am running the api locally on 3010, not httpsed becuase that layer I cover with nxing. So technically speaking this config should work:

``` javascript
"api": {
    "https": false,
    "host": "localhost:3010",
    "prefix": "/api/"
  },
```

but it obviously doesn't, otherwise where would the fun be.

Nothing is loading from the DB and I get no error what so ever on the console (ignore the  `NODE_TLS_REJECT_UNAUTHORIZED=0` that get's rid of node not accepting unsigned https certificates which are the case in gotsentimental and also ignore the gotsentimental spam, I asked them if they could slience their logs with some setting):

``` bash
me$ NODE_TLS_REJECT_UNAUTHORIZED=0 npm start

> js16seminar@0.0.1 start /home/cdallago/web
> NODE_ENV=development node ./server/server.js

Development Express server running at localhost:8080
[main][INFO] Episodes updated
[core/db][INFO] connected.
[crawler/blacklist][WARN] filtered unclassified: Helya
[crawler/blacklist][WARN] filtered unclassified: Qyburn
[crawler/blacklist][WARN] filtered unclassified: S'vrone
[crawler/blacklist][WARN] filtered unclassified: Tickler
[crawler/blacklist][WARN] filtered unclassified: Weeper
webpack built 3adfb5e0d1add3bfb6e9 in 26667ms
[main][INFO] Characters updated { total: 2028, filtered: 517, found: 1511, inserted: 0 }
[crawler/mobile][INFO] [1/1511] MCRWLD Leo Lefford { found: 0, inserted: 0 }
[crawler/mobile] Wrote CSVs for Leo Lefford
```

This actually happened with gotsentimental as well, so I modified nxing to listen on localhost as far as API goes, and ignored the unsigned or invalid certificates.. and it worked.
HOWEVER, they also had to change their code to introduce the port number for the requests. Their config on my machine looks like:

``` json
"api": {
                "https": true,
                "host": "localhost",
        "port": "3010",
                "prefix": "/api/"
}
```

You can have a nice read at the discussion [here](https://github.com/Rostlab/JS16_ProjectD_Group4/pull/110#issuecomment-204804573) and the commit that changed the port stuff [here](https://github.com/Rostlab/JS16_ProjectD_Group4/commit/76d7e11119da3ef05878b7eb19d4872c4e790260)

**Comment by TheZoker** [comment]
@sacdallago Same result for `NODE_ENV=production`?

**Comment by sacdallago** [comment]
Tried that, doesn't work with all three options: http/https with and without port number.

I think you have to write that port thing I suggested for every call

**Comment by TheZoker** [comment]
@sacdallago Can you please try it with these changes?

**Comment by sacdallago** [comment]
@TheZoker [This](https://github.com/Rostlab/JS16_ProjectD_Group4/commit/76d7e11119da3ef05878b7eb19d4872c4e790260) is the step that is missing, I think! [This](https://github.com/Rostlab/JS16_ProjectF/blob/develop/app/network/Api.js#L10) **seems** like a place where it can be used

**Comment by TheZoker** [comment]
@sacdallago Yes, just found the same line :D
Will fix it :)

**Comment by sacdallago** [comment]
# Major Update

I got it now, I made such a stupid mistake. Let me explain.
1. The /characters page (for example) `GET`s the data form the API from the client via a call. In that case, you obviously want to have the `api.got.show` as address.
2. For **INTERNAL** calls, for example if you call the API from the backend side of node, you would need the `localhost` flavored version with the port number.

To understand the difference here is crucial. And this brings me to the following questions:
1. Do you ever use the URL-encoded `token` to perform calls in the frontend? (security breach ahead)
2. You should separate the configuration for the frontend calls and the backend calls (because you have some of them, right?)

This is of interest for everyone ( @mammuth @jorjo1 @mina-zaki @yashha @Andrew094 ) because you know your code better than enyone else

**Comment by TheZoker** [comment]
@sacdallago So can the [pull-request](https://github.com/Rostlab/JS16_ProjectF/pull/304) be closed?

I just added the port: https://github.com/Rostlab/JS16_ProjectF/pull/304/commits/4bd4c155917b62e4e86d24169eaf94b13eea8dc0

**Comment by sacdallago** [comment]
No.
- There are problems with your commit:
  1. It doesn't build
  2. What if the port number is not defined in the config (default 80 or 443 depending on the protocol)? I would just leave that `: +...` out.
- We have to figure out if someone performs API calls in the backend. If that is the case, the config needs to be changed and so does the code

**Comment by TheZoker** [comment]
- Fix the build issue: https://travis-ci.org/Rostlab/JS16_ProjectF/builds/121665584
- What do you mean by "leave that `: +...` out."? If I remove the `:` the baseUrl will be `https://api.got.show3010/api` and that will not work. Or did I got you wrong? 

I added a port fallback: https://github.com/Rostlab/JS16_ProjectF/pull/304/commits/68edfdef7684a77e8dbc1c446f232f0fe118a3af

**Comment by sacdallago** [comment]
The fallback is ok! I would have simply left out the entire `:` part if the port was `undefined`, instead of adding the `80` or `443` :) But I guess that should work as well.
Now I'm waiting for the other ones (@mammuth @jorjo1 @mina-zaki @yashha @Andrew094 ) to tell me if they ever use API calls server-wise + if they ever use the `token` client-wise

**Comment by TheZoker** [comment]
@sacdallago Gotcha! So should I leave it this way or just remove the port if its undefined? What's best practice here?

**Comment by sacdallago** [comment]
@TheZoker I would leave it out :) It's redundant information ( http = 80, https = 443 )
But: up to you :wink:

**Comment by yashha** [comment]
You can reopen it, the next time you have error.
