### ISSUE TITLE
Integration of Landingpage 

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#275]
#169

We have already our first landingpage and we need to integrate it now in our serverside.
That means we have to create an static html file from the markdown.
So we need static images from for example the map and the chart and static plod values. In the supposed areas.

Can you do this mina? 
Any questions ask me :)

@Andrew094 if you want to do this, because you are our static guy, post here :)

**Comment by mina-kleid** [comment]
@Andrew094 can you jump on this ?

**Comment by jorjo1** [comment]
I will join here from tomorrow.

**Comment by Andrew094** [comment]
yes, is there already a branch for this ?

**Comment by gyachdav** [comment]
@marcusnovotny we will launch without landing pages :disappointed: 

Not your fault just the nature of the biz. 

We will however should now set a target to publish **one landing page every two days** until we have all the pages we planned originally. 

So, the first landing page to be release post release will be the Jon Snow page and the target will be tomorrow - Tuesday April 11.  @jorjo1 is still assigned to this task from F and @togiberlin is should deliver by the end of today the infographic for the page.

**Comment by yashha** [comment]
The jon snow landingpage is finished, It just has to be merged.
https://github.com/Rostlab/JS16_ProjectF/pull/384

**Comment by gyachdav** [comment]
ah really? did you get the info graphic from @togiberlin ?

That's really cool news!

**Comment by yashha** [comment]
Yes it is already inside it.

**Comment by marcusnovotny** [comment]
Last page coming tomorrow!

**Comment by gyachdav** [comment]
and also the last landing page from my end Ramsay vs. Reek will come in tomorrow.

**Comment by sacdallago** [comment]
So let's say that tomorrow we have **ONE** PR for all landing pages missing.

Who wants to be the last one to touch the code in a while @jorjo1 @yashha @mammuth ?

**Comment by mammuth** [comment]
Öh, since @yashha told me to merge the landingpages we currently have, I did so. So we will merge new landing pages separately.

Closed via #384
