### ISSUE TITLE
Fix map centering

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#277]
The positioniong of the map is set wrong somewhere. 

I think this happened when trying to get rid of the sidebar in combination of trying to make it fullwidth and some more stuff.

@jorjo1, wanna take this as our dedicated CSS-guru? :kissing_heart: 

Hint: There are three pages it needs to work on: home, map, character-detail

**Comment by jorjo1** [comment]
I'll also try to move the sidebar to the left side, or remove the white space below it, simply because there is no use of it when one simply surfs through our content.

**Comment by jorjo1** [comment]
#207
