### ISSUE TITLE
Sorting by PLODs

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#280]
@mina-zaki the sorting of PLODs should be comparatively easy now that we know how it all works.
1. Call the PLODs for all characters
2. `map` to the characters array the relevant plod for that character... `var charWithPlod = charaters.map(function(element){ element.plod = plod.getFromName(element.name); return element;})`
3. sort by the PLOD, use the group with the better predictions

**Comment by sacdallago** [comment]
P.S.: keep in mind that some characters, ~200, don't have a PLOD. Just put these at the end of the sorted array :)

**Comment by mina-kleid** [comment]
@sacdallago how can i know which group has a better prediction ?

**Comment by sacdallago** [comment]
The plods with description `gotplod`
Right @goldbergtatyana ? Not the `gotarffplod`

**Comment by sacdallago** [comment]
@mina-zaki there's also an API call to `GET` PLODs by description ;) that should speed up the request a little (aka: you don't have to get all the PLODs)

**Comment by mina-kleid** [comment]
yea you mean getting plods by Algorithm? already doing that if we only using one algorithm

**Comment by mina-kleid** [comment]
Done and waiting for approval on the pull request

**Comment by goldbergtatyana** [comment]
yes, i think so @mina-zaki and @sacdallago: 
gotplod = better predictor of Group 6
gotarffplod = worse predictor of Group 7

@mina-zaki you could run a small test: if you get PLOD ~12% for Jon Snow with gotplod, then it is the function to go with. The worse function gotarffplod should return PLOD ~100% (and this is not what we want to show)

**Comment by mina-kleid** [comment]
This supports the case, we go with gotplod

http://cl.ly/0y332Q372h2W

**Comment by goldbergtatyana** [comment]
Cool, thanks for checking, @mina-zaki!
