### ISSUE TITLE
No csv files are loading atm

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#290]
![image](https://cloud.githubusercontent.com/assets/4728786/14338038/b9653dc4-fc73-11e5-8651-26df19c57e2b.png)

**Comment by sacdallago** [comment]
Are you using a database with all the necessary data already? It might take some time (18h) to fill up all the data.. I can provide you with a dB if you don't have one.
@julienschmidt can you follow up on this one as well? :)

**Comment by jorjo1** [comment]
Is this a probable cause?
![image](https://cloud.githubusercontent.com/assets/2246472/14346745/d235eb10-fcb3-11e5-9688-d2dde30568e4.png)

``` bash
[crawler/mobile][INFO] [108/2922] MCRWLD Walda Frey (daughter of Rhaegar) { found: 0, inserted: 0 }
[crawler/mobile] Wrote CSVs for Lothar Frey
[crawler/mobile] Wrote CSVs for Walda Frey (daughter of Rhaegar)
[crawler/mobile][INFO] [109/2922] MCRWLD Damon Lannister (lord) { found: 0, inserted: 0 }
[crawler/mobile] Wrote CSVs for Damon Lannister (lord)
[crawler/mobile][INFO] [110/2922] MCRWLD Raymun Fossoway { found: 0, inserted: 0 }
[crawler/mobile] Wrote CSVs for Raymun Fossoway
[crawler/mobile][INFO] [111/2922] MCRWLD Grazdan mo Eraz { found: 0, inserted: 0 }
[crawler/mobile][INFO] [112/2922] MCRWLD Damon Lannister (lord) { found: 0, inserted: 0 }
[crawler/mobile] Wrote CSVs for Grazdan mo Eraz
[crawler/mobile][INFO] [113/2922] MCRWLD Gerald Gower { found: 0, inserted: 0 }
[crawler/mobile] Wrote CSVs for Damon Lannister (lord)
[crawler/mobile] Wrote CSVs for Gerald Gower
[crawler/twitter][WARN] Rate-Limited. Timeout: 697s [Thu Apr 07 2016 11:40:18 GMT+0200 (CEST)]
```

**Comment by sacdallago** [comment]
This seems to be a good cause :D You might want to clean the mongodb you use to store the tweets?

**Comment by yashha** [comment]
I let the heroku server run of a good ammout of time and there were ni csv files
You're right the problem could be the mongodb
I swipe it propably in an hour and rerun the server

**Comment by jorjo1** [comment]
Or it could be a problem if we are too many servers at once trying to scrape info from twitter with the same API key?

**Comment by sacdallago** [comment]
Looks more like a mongo problem to me! Remember that the crawler produces something like 500mb of data in about 24h of runtime

**Comment by yashha** [comment]
@jorjo1 Your error message was has his cause in the maximum of mongodb database was reached

**Comment by yashha** [comment]
I reset the mlab db now but it still doesn't work
the csv files are being written but they are not being served by express and the react-router is being served instead

`2016-04-07T11:41:10.752706+00:00 app[web.1]: [[36mcrawler/mobile[0m] Wrote CSVs for Marq Grafton`
https://got-stats.herokuapp.com/d4/csv/Marq%20Grafton.csv

The strange thing is that the episodes.csv are being served
https://got-stats.herokuapp.com/d4/csv/episodes.csv

**Comment by yashha** [comment]
So i found out that
https://got-stats.herokuapp.com/d4/csv/Marq%20Grafton.csv
is of couse not working because the files are saved with an underscore
but
https://got-stats.herokuapp.com/d4/csv/Marq_Grafton.csv
Isnt working too

The other thing is this is working:
https://got-stats.herokuapp.com/d4/csv/Aegon_Blackfyre.csv

**Comment by yashha** [comment]
It seems like its working now, it just takes its time :)
