### ISSUE TITLE
Base Structure and Layout

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#3]
- What information do we need to display?
- What the user needs to interact with heavily?

Let's try to get clear about the content we want to show to find out how to structure our base layout.

**Comment by mammuth** [comment]
### Data:
- Characters PLOD (percent likelihood of death) (provided by Project B)
- Character-Location association on a map (provided by Project C)
- Whom people liked the best from the last episode? (provided by Project D)
- Character Popularity over time (provided by Project D)
- Characters sentiments on twitter over time (provided by Project D)

If I missed anything, feel free to edit this comment and add it.

**Comment by yashha** [comment]
We will do an creative and collaborative online meeting **today evening**.
At the moment Max Muth and Georgi Anastasov and me will attend.
Topic will be design and structure.
Time: **18:00 ~~between 6 and 7~~** until open end.
If you want to join and help us to get ideas for a nice UI, just **comment** this issue.

**Comment by mammuth** [comment]
### Pages and their Content:
- Home
  - PLOD Top3 (?)
  - Whom people liked the best from the last episode (App by Project D)
  - Character Sentiments Top5 (?)
  - Map App by Project C
- Characters List / Catalogue (?)
- About
  - Description of this seminar, Github Link, list of all contributors, ...

Character Detail Page:
- Corresponding House (?)
- PLOD (App by Project B)
- popularity from the last episode (?)
- Popularity over time (App by Project D)
- Sentiments on twitter over time (App by Project D)

If we decide to add the points with a _?_ we should open an Issue on the corresponding project repo and ask whether they build an API for that.

Just my first thoughts on how to structure the data. Let's see what we get in our meeting this evening.
Feel free to update/edit this comment according to our decisions.

**Comment by jbraito** [comment]
Hi guys,
first of all thank you for the effort during the past days. As I had my last exam yesterday I couldn't involve myself so far, but from now on I'm looking forward to support you in the project. I already skimmed through your conversations about the Technology stack and the hosting platform as well as the conversations in the google groups 8 and 9. Todays meeting comes a little bit at short notice so unfortunately i just can make it for the first 30 min. Let me know

**Comment by yashha** [comment]
So we are here https://meet.jit.si/jsseminar1
You can stop by if you want
