### ISSUE TITLE
Integrating double projects?

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectF#30]
As the Project B and D are developed twice (or at least there exist two similar applications), how will you integrate those?

Will you offer two applications and the user will be able to choose between them or will you merge them in some ways?

**Comment by mammuth** [comment]
We're not going to include two different "apps" for the same thing.

As far as I know there are discussions about how to bring those two projects together into one (by using average metrics or whatever). However this is nothing we (Project F) will be in touch I guess. This needs to be dealt by your Projects B and D together with the Integration-Project E.

**Comment by sacdallago** [comment]
Slightly too fast on closing issues here :D https://github.com/Rostlab/JS16_ProjectE/issues/8

**Comment by mammuth** [comment]
Yep, followed the corresponding discussion on the repo of E.

Seems to be unnecessary "complicated" because now we have to think about how to tell the user why there are different numbers about the sentiment and PLOD. 
Will probably be an awesome UX.

Well, our problem now... :+1:

**Comment by sacdallago** [comment]
Oh well, not that bad. You think in finance they use just one predictor to call investments? :D
Just put a nice switch on top "predictor 1" | "predictor 2" , that should do the trick. There's also components for that right out of the box from bootstrap :D

**Comment by mammuth** [comment]
Guess this meta-like issue can be closed. If there's something else, feel free to open a specific issue.
