### ISSUE TITLE
jQuery and X-UA-Compatible tag missing on main page

### ISSUE THREAD

**Issue by TheZoker** [Rostlab/JS16_ProjectF#302]
I just validated the page with bootlint:
http://www.bootlint.com/?url=https:%2F%2Fgot-stats.herokuapp.com%2F

Issues:
- [ ] https://github.com/twbs/bootlint/wiki/W005
- [ ] https://github.com/twbs/bootlint/wiki/W002

**Comment by jorjo1** [comment]
Hi
we can ignore that.

> You're not using any of Bootstrap's jQuery plugins; or
> Your website's JavaScript is concatenated into one file (or just a few files), such that jQuery isn't loaded from its own separate file; or
> Your website uses a JavaScript packaging system (e.g. Browserify), such that the jQuery object isn't exposed to the global namespace.

The W002 - I fixed that. #306

**Comment by TheZoker** [comment]
Sorry read that to late. I added the right jquery file and added `.min` to the bootstrap files.

If you're not using jquery at all, we should remove it from the dependencies
