### ISSUE TITLE
Justify text throughout the website

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#309]
Please use align:justify for all paragraph text

**Comment by sacdallago** [comment]
You know that this is one of those things that bothers me like hell @gyachdav ! :D I don't get how they don't make this default behavior in frameworks like bootstrap

**Comment by mammuth** [comment]
Good point, I will justify all paragraphs.

@sacdallago the answer to your question is pretty straight forward. How should they apply it in a general way, so it works out for everyone? 
Just making the whole body or all paragraphs justified might crash something. Like here (those thumbnails are basic bootstrap components, btw :wink:):
<img width="1050" alt="screen shot 2016-04-08 at 19 34 35" src="https://cloud.githubusercontent.com/assets/3121306/14392325/125345e0-fdc1-11e5-917f-962944c51a38.png">

**Comment by mammuth** [comment]
Done in https://github.com/Rostlab/JS16_ProjectF/commit/4b94fef56c886b8bbafa778ace2bc8d7b32689b5

(@sacdallago, no need to complain about committing directly to develop - thought I was in a new branch... turned out I was wrong when committing :grin: )
