### ISSUE TITLE
Project D5 API

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectF#31]
Hey there :) 
Group 5 (They are doing the Twitter Sentiment Analyses) and I had decided to provide you with the following functions in the npm Package. (As soon as they are implemented and passed the tests you will get them)

The functions are:
- getSentimentForName(name,date) - returns {posSent: Number, negSent:Number, numTweets:Number}
- getSentimentForNameTimeframe(name, startDate,endDate) - returns Analysis over a timeframe (same as above)
- topSentiment (number, startDate,endDate) - returns Array of names, which are most loved. with length=number. Ordered!
- worstSentiment (number, startDate, endDate) - returns Array of most hated Characternames. Ordered.
- mostTalkedAbout (number,startDate, endDate) - returns Array of Characters, where the most Tweets exist in a certain Timeframe. Ordered!
- topControversial (number, startDate,endDate) - returns Characters, which have the highest difference between positive and negative sentiments. Ordered.
- sentimentPerEpisode(name, season, episode) - returns sentiments for name from airing date and the week after on (season,episode).

If you do not like something please comment it. After tomorrow there won't be changes on the functionnames, arguments or semantic. Of course they need to be implemented, but you can be assured that they will exist and accesible in the project.

You can also request more functionality. Comment here or make an Issue in ProjectD_Group5.

Here are the teammembers of the Project:
@kajo404 @Logarythms @vanp33 

I am from Project E (Integration). If you have questions, I will do my best to answer them.

**Comment by kajo404** [comment]
@sacdallago is this what you had in mind? we store the sentiment information in the database of team A and provide these functions for team f

**Comment by sacdallago** [comment]
Exactly what I thought about!

**Comment by jcebel** [comment]
To understand the output:
The Sentiment-Analyses-Algorithm, determines if a tweet is either nice or nasty and how nice or nasty. This is expressed on a scale between -6 to 6. (6 beeing very nice).
The Application adds the results of the analyses of all the positive tweets in the posSent-property and all the negative tweets in the negSent-property. 
So there can be stored Numbers high above the 6 or below -6. 
The numTweets-property gives you the number of Tweets, which are posted in the specified timeframe over the character.

**Comment by mammuth** [comment]
For me this looks good!

PS: I'm curious about the top, worse, mostTalkedAbout and topControversial :blush:

**Comment by jcebel** [comment]
About exceptions: As you will need to interprete the Exceptions, it is important, that you tell as which Information you need if an Error occurs (e.g. if you're searching for Donald Trump or if there exists no Data for this specific timeframe).

I made the following Searcherror for testing reasons, but feel free to formulate your own needs. :-)

``` javascript
function SearchError(message, date, searchedName){
        this.name='SearchError';
        this.message=text || 'Some Failure happpened while searching for a SentimentAnalyses';
        this.stack= (new Error()).stack;
        this.date= date;
        this.searchedName= searchedName;
    }
```

**Comment by mammuth** [comment]
I think it might be interesting to embed the latest X top-tweets regarding a certain character on its detail-page. 

Since you guys are already using the Twitter API what do you think about adding a function which returns links of the latest top tweets?

**Comment by kajo404** [comment]
Some additions:
We will provide 2 additional functions. 

runTwitterAPI(char,startDate) this runs the REST API to collect all tweets from the startDate until now (subject to change)

runStreamingAPI(char,time) runs the streaming API for time seconds

Also, can we replace all charName paramaters with the _id used in A's database? This makes identification a lot easier since _id is unique.

@mammuth I think we can return the twitter id's for some trending tweets but we cannot guarantee that they are the most popular

**Comment by mammuth** [comment]
If _id is unique and consistent over all projects this is the way to go. Because then we can pass this single character id to every project-component we're using.

Trending tweets :+1:

**Comment by sacdallago** [comment]
Can you come tomorrow and explain what this is about to me? I lost track here and I have to go trough a few things before midnight :D :D :D

**Comment by kajo404** [comment]
Ok so now that we cleared some things up offline here are some updates.
The functions listed above with take a json with the parameters and a callback function.
The callback function will take the a json as a parameter. I will gill our index.js with dummy data so you can have a look and know what to expect. I will update here when it is available

**Comment by jcebel** [comment]
You can find the package at npm under the name 'gotdailysentiment'. Documentation will come. As long it is still missing consult our Readme in the Repository.
Please be aware of the fact, that the functions are not implemented yet. But they return some dummy data to play. Enjoy :-)
I will close this issue as Project D5 does not expect that they have to change the functions anymore- still: feature frreeze is 21st so maybe, maybe they will.

**Comment by jcebel** [comment]
Hey I'm sorry to bother you again. We had to change the configuration part of Project_D-5.
It is explained in the Readme or at the [npm page](https://www.npmjs.com/package/gotdailysentiment) in the section **Usage**.
You may close this issue, if there are no other questions :)

**Comment by mammuth** [comment]
Thx @jonny3576.

Questions:
- On npm in the configuration of the package it says something like: _"database -> This is the access to the database, where the tweets are stored by the package "_ I don't quite get this; we're not running an own database for the page, we just query our stuff from A.
- Something different: Could you remind me how the other Twitter-Group is providing their data to us? Do they have a npm package as well that we can use like this one?

**Comment by kajo404** [comment]
Hi @mammuth , I am from Group 5. Don't worry about the configuaration. We will provide you with everything you need to run the package. 

I do not know what the other group is doing though :/

**Comment by sacdallago** [comment]
The other group is one step behind you @kajo404 , https://github.com/Rostlab/JS16_ProjectD_Group4/issues/44

**Comment by jcebel** [comment]
This is something You can ask @CavidSalahov. He is responsible for integrating D4.

**Comment by jcebel** [comment]
We concluded yesterday, that no external database will be needed at this point of time. So configuration will be slightly changed. I will update the readme as soon as [this](https://github.com/Rostlab/JS16_ProjectE/issues/17) has been solved.

**Comment by jcebel** [comment]
Ok you may get the first (hopefully) working package at npmjs. Use it but please keep in mind that it only contains dummie data and functionality, which will be implemented in the upcoming days.
