### ISSUE TITLE
Friday video meeting 

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#313]
@Rostlab/js_cs_sose_2016_students 

Hello everyone,
we are having a video meeting about Project F tomorrow, the 8.04.2016. Here are some further details:

**When** Fri 8 Apr 2016 14:30 – 17:30 Berlin
**Where** `https://meet.jit.si/GoTJS` [Join video call](https://meet.jit.si/GoTJS) :movie_camera: 

Last chance! So if you have a nice idea, want to share something or simply want to spy on us, please be welcome and join this conversation. Sleep well!

**Comment by goldbergtatyana** [comment]
@Rostlab/js_cs_sose_2016_students

Thanks @jorjo1 for inviting everyone to our final website content & design call today!

**Update:** We moved the call to **3pm** today!
To join the call, just follow the link **[https://meet.jit.si/GoTJS](https://meet.jit.si/GoTJS)**

See you soon!
