### ISSUE TITLE
Euron Greyjoy has 2 different PLOD's on the website

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#316]
https://got-stats.herokuapp.com/characters/Euron%20Greyjoy 
PLOD 0.932%

On the start page PLOD: 94.2%

p.s. 
love the new release to staging!

**Comment by goldbergtatyana** [comment]
One more comment to PLODs: please round the numbers such that 97.2% becomes 97% and 35.4% becomes 34%.

There is no information content in the value after the comma. Thanks!

**Comment by sacdallago** [comment]
:O It seems that on the characters page they are using the `gotarffplod` alg @mina-zaki 
https://api.got.show/api/plod/bySlug/Euron_Greyjoy

**Comment by yashha** [comment]
Why https://api.got.show/api/plod/bySlug/Petyr_Baelish
has gotarffplod of 1, thats really strange when I show that he has a chance of 100%

**Comment by goldbergtatyana** [comment]
its fine that the prediction for him to die is 100%, @yashha 

However, **gotarffplod is the worse predictor** and its result only replaces XX% in the description of predictor_1.
