### ISSUE TITLE
Homepage PLOD for antagonists

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#326]
Hi party people, we have two little adjustments in the antagonists part of the page:
1. Make the images "full screen" for the div. You can better achieve this by using CSS and the `background` attribute in my opinion, even if it's in-line style.
2. The plod value is a little too small. We could solve this problem in an artistic way by putting the tombstone _inside_ the picture and write the PLOD value (only) inside the tombstone.

---

![asdasd](https://cloud.githubusercontent.com/assets/6240943/14387871/a2687efe-fdab-11e5-8125-4c99bf425b89.jpg)
# sacdallago

---

{_Such wow picture_}

**Comment by jorjo1** [comment]
Hi, @sacdallago !
First: HAHAHAHAHAHAHAHA! That was unexpected :dart: 
Second: I am being _asynchronously_ creative. Stay tuned :D

**Comment by goldbergtatyana** [comment]
Haha @sacdallago, this a very clear example of visualization! 

Below the images of antagonists, I suggest to write:
The tombstone shows our predicted likelihood of death. <link>How do we predict likelihood of death?</link>
