### ISSUE TITLE
Characters List

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#33]
Displays all characters. 

Might have sorting and search functionality.

Each element links to a character page from issue #23

**Comment by mammuth** [comment]
ToDo:
- [x] Searching by (at least) name

**Comment by mammuth** [comment]
Done by #96

**Comment by jorjo1** [comment]
This should be redesigned

![image](https://cloud.githubusercontent.com/assets/2246472/14161081/3870aee8-f6e1-11e5-99d5-af6f42200cfc.png)

**Comment by gyachdav** [comment]
Sorting titles:
- [ ] Name A - Z
- [ ] Name Z - A
- [ ] Most popular (book) -- this is the default sorting
- [ ] Most liked (Twitter)
- [ ] Most hated (Twitter)
- [ ] Survival chance (comment: this is 100 - death_chance)
- [ ] Death chance

**Comment by jorjo1** [comment]
We are working on displaying data for top5-s, but we are realistic and think that "Top 5 most dangerous house Group 6" will not be part of the ranking because it's not implemented and it would slow us down.

Are they changing at all? Can we still hardcode them somehow? @gyachdav

**Comment by goldbergtatyana** [comment]
None of the results, but twitter sentiments, are going to change anymore!

Please see https://github.com/Rostlab/JS16_ProjectF/issues/40 for the discussion of TOP5s
