### ISSUE TITLE
[LEGAL] HBO ASSETS

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#341]
I got a no. 
@gyachdav @goldbergtatyana @sacdallago @mammuth @yashha 

> Hello Georgi,
> 
> Thank you for contacting HBO with your inquiry and for your interest in HBO. Unfortunately, we will have to decline this request. We do not customarily allow our content to be utilized in this way.
> 
> HBO Consumer Affairs

:angry:

**Comment by mammuth** [comment]
Delete the mail!
We didn't read it! :see_no_evil:

**Comment by gyachdav** [comment]
Yes Ignore the mail for now.

**Comment by jorjo1** [comment]
What mail? :wink:
