### ISSUE TITLE
Same version, different behavior on two hosts

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#346]
on www.got.show i see

![screen shot 2016-04-08 at 8 10 52 pm](https://cloud.githubusercontent.com/assets/4074881/14400418/f8a1b438-fdc5-11e5-943b-22f1ab86f953.png)
PLOD presented **under** images but heading doesnt show. 

on heroku i see: 

![screen shot 2016-04-08 at 8 10 20 pm](https://cloud.githubusercontent.com/assets/4074881/14400429/0b9996a0-fdc6-11e5-9632-a2dc2be949ba.png)

notice PLOD at 0% and no heading

Both show v0.0.21 in the footer. 

Which is which? and how come the heading and PLOD are still broken?

**Comment by jorjo1** [comment]
@gyachdav the PLOD has a default value of 0 and gets changed when the information is loaded. The inconsistancy between www.got.show and herokuapp is that we have no acces to the server, but only @sacdallago 

About the versions, I have no explanation right now o.O

**Comment by gyachdav** [comment]
the ver on heroku works now, thanks. I'm guessing that the tag for the version number is being picked up from github? (otherwise I cannot explain why both versions show the same number even though @sacdallago did not install the latest on got.show)

**Comment by jorjo1** [comment]
Yep, it's pulled directly from github

>  fetchVersion() {
>     $.ajax({
>       url: "https://api.github.com/repos/Rostlab/JS16_ProjectF/tags",
>       type: "GET",
>       crossDomain: true,
>       success: function (response) {
>         $('.build-version').text(response[0].name);
>       }
>     });
>   }

**Comment by gyachdav** [comment]
mystery solved, thanks!

**Comment by sacdallago** [comment]
:D that's sort of inconvenient 
You basically always have the last version running... althouuuughhh :D :D :D
