### ISSUE TITLE
Brandon stark dead?

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#359]
Can you please check how bran stark is dead in the webpage but not in the DB?  Is this a problem with pulling the wrong entry from the DB again? 

https://got-stats.herokuapp.com/characters/Brandon%20Stark

**Comment by yashha** [comment]
The problem is that he has a date of death :(
https://api.got.show/api/characters/Brandon%20Stark?strict=true

**Comment by sacdallago** [comment]
@gyachdav if that's the case on the wiki, then the problem is at the root

**Comment by goldbergtatyana** [comment]
i think the problem is that we have brandon stark who is dead https://got-stats.herokuapp.com/characters/Brandon%20Stark and bran stark, who is a different character, and who is alive https://got-stats.herokuapp.com/characters/Bran%20Stark

:smile:

**Comment by gyachdav** [comment]
okay i think i know what the problem is. PR coming soon.
