### ISSUE TITLE
Change attribution order

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#362]
Please, for political reasons:

Put the attribution to the "A Wiki of Ice and Fire" / http://awoiaf.westeros.org/index.php/Main_Page absolutely in first position in https://www.got.show/attributions

Thx

References: #234

**Comment by sacdallago** [comment]
Also put somewhere on the [about page](https://www.got.show/about), maybe after the Attributions title and before the paragraph that redirects to the relevant page, a paragraph like:

> Most of our data was - and is periodically- scraped by [A Wiki of Ice and Fire](http://awoiaf.westeros.org/index.php/Main_Page). Contributing to this wiki will enhance this portal greatly, so make sure you drop a visit to our wiki-partners and request an account.

-- or something very _american_ like this

Again: political reasons / trust me on this one

**Comment by mammuth** [comment]
Closed by https://github.com/Rostlab/JS16_ProjectF/commit/897079c62c35fa871665f80e9d0018c07ae3065a
