### ISSUE TITLE
Twitter sentiment trendline

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#363]
[This character](https://www.got.show/characters/Jaqen%20H'ghar) is the "most loved" character according to https://www.got.show/ranking .
The twitter graph though doesn't appear to have any information on it.
This is not true, as we are running an instance with the same data but only the graph under csv.got.show and this char clearly has a lot of twitter data related: http://csv.got.show/Jaqen_H_ghar

My take is: look at the name! Could it be that the `'` is causing the problem? Could this be the cause for other pretty important characters not having twitter data related (also on the home page there are some chars with this problem)

CC @julienschmidt @marcusnovotny @santanumohanta 

Last but not least: if you want to redirect the users to the csv page for "a full screen view" of the graph, I don't think that might be such a bad idea. Maybe a one sentence after the graph itself saying

> To view a bigger version of the above graph, you can visit csv.got.show

and then in the url to csv.got.show you put the _¿slug?_ of the character.

**Comment by yashha** [comment]
yea  the problem is the ' in the name
we have to replace it with an _ before we send the csv request on the client
https://www.got.show/d4/csv/Jaqen_H_ghar.csv

Edit: thanks for the notice :)

**Comment by sacdallago** [comment]
I also noticed a 0% PLOD, so maybe, just maybe, there's also a problem there?

I think _slugs_ interpret `'` as `_`

**Comment by marcusnovotny** [comment]
Project A switched the slug for us since the ' caused problems. Other characters don't have special characters in their name, so there shouldn't be any more issues like that. yashha is right.

The ranking on the page is outdated anyway. DB dump will be up shortly, the ranking looks like this at the moment:

Most Popular

```
Jon Snow
Hodor
Tyrion Lannister
Daenerys Targaryen
Varys
Arya Stark
Jaime Lannister
Bronn
Ygritte
Margaery Tyrell
```

Most Hated

```
Grey Worm
Theon Greyjoy
Walder Frey
Meryn Trant
Jon Arryn
Elia Martell
Joffrey Baratheon
Lysa Arryn
Ramsay Snow
Rakharo
```

I'm confident that we have full data on all major characters now

**Comment by gyachdav** [comment]
Grey worm most hated? really? and ellia martell? what did she ever do to anyone?

**Comment by marcusnovotny** [comment]
It's from negatively phrased tweets about events that happened to them. For Grey Worm it's episodes where his life was in danger (Sons of the Harpy attack), Elia Martell was apparently mentioned in a lot of unhappy tweets after Oberyn died. It's hard to filter stuff like that out. Best solution I can come up with is to rephrase "Most Hated" into "Most negative mentions"

**Comment by gyachdav** [comment]
yes please rephrase. most hated will raise a lot questions and undermine our credibility.

**Comment by marcusnovotny** [comment]
Probably easiest to just switch the headline on the website, what do you think?

**Comment by gyachdav** [comment]
You mean the heading in the ranking page? yeah sure, make a note on https://github.com/Rostlab/JS16_ProjectF/issues/40

**Comment by marcusnovotny** [comment]
Done
