### ISSUE TITLE
Expectations

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#37]
Dear all,

we tutors meet and discusses what we expect from you (basically, we did some of your work :P), and came up with the following suggestions/requirements:
1. Routes
   - [x] We would like a list of routes (e.g. /, /character/? , /map ,...)
   - [x] You should set up these routes
   - [x] Set up default and 404 route
2. Views
   - [x] Write down metadata ( **!!!!!!! Meta data is probably the most important thing ever, ever, ever. I cannot stress this out enough. Remember that search engines crawl this. REMEMBER: Facebook and Twitter have their own definitions for meta tags!!!!!** )
   - [x] Which views, e.g. statistics, map, PLOD (ranking and single view), character, sentiments,...
3. User Experience
   - [x] Event with React
   - [x] Exception handling
4. Models
   - [x] Basically mirror the models of project A: statistics, character, cities, locations,...
5. Layout / Design
   - [x] Mockups/prototypes (of all components/views)
   - [x] Menus
   - [x] Header + Footer
   - [x] Color Scheme (possibly consistent with **C10**
   - [x] Common CSS definitions

**Comment by mammuth** [comment]
**1.1. List of Routes:**
- /
- /characters
- /characters/:id
- /map
- /ranking
- /about

**Comment by gyachdav** [comment]
Next, please:
- [x] break down this issue into separate issues
- [x] assign issues to members according to the roles we all agreed on today
- [x]  assign deadlines 
- [ ] once we are satisfied with the way you converted this issue to several, properly defined and measurable issues. we will close this one

**Comment by gyachdav** [comment]
We decided to keep this issue open and invite @Rostlab/js_cs_sose_2016_students to contribute. 

(@Rostlab/js_cs_sose_2016_students check out [staging on heroku](got-stats.herokuapp.com) to see the current state of the web app)

basically this should serve as a wish list for features we would like to see on the website. Remember this is **not a base requirement list *\* for alpha but instead more of a **nice-to-haves** and **will-implement-later**. 

Here are a couple of thoughts:
- [ ]  "For developers": a. reference  the API docs from A (e.g. https://got-api.bruck.me/doc/)  b. reference GH repos, c. reference to project reports to reports from B,C,D d. reference to project report from E on tools used, standards, conventions etc. Basically everything devs would need to extend capabilities. 
- [ ] A widget that will allow people to add in their wish list (“I want to see statistics about.. “)

**Comment by mammuth** [comment]
Closing since it's horrible outdated and got useless.
