### ISSUE TITLE
Daella_Targaryen_(daughter_of_Maekar_I) is currently dead

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#371]
https://got-stats.herokuapp.com/characters/Daella%20Targaryen%20(daughter%20of%20Maekar%20I)
Daella_Targaryen_(daughter_of_Maekar_I) is currently dead, but she is listed in 3 with highest death chance in character listing

Its because she has no gotplod in this request
https://api.got.show/api/plod/bySlug/Daella_Targaryen_(daughter_of_Maekar_I)
https://github.com/Rostlab/JS16_ProjectA/issues/142

**Comment by mammuth** [comment]
Closed by #373
