### ISSUE TITLE
Faces of some antagonists zoomed in too much

### ISSUE THREAD

**Issue by goldbergtatyana** [Rostlab/JS16_ProjectF#375]
For example of Kevan Lannister (see below). Let me know if you think I should go over the pictures and check that we don't have such cases, aka all pictures are beautiful :heart: 

https://rostlab.org/~goldberg/antagonists.png

**Comment by jorjo1** [comment]
on mobile
![image](https://cloud.githubusercontent.com/assets/2246472/14412323/8b7e1eae-ff60-11e5-9648-bb3b4061e1ec.png)
to be fixed, really strange behaviour.. will fix in an hour

**Comment by yashha** [comment]
Fix the names please in the same pr 
![image](https://cloud.githubusercontent.com/assets/4728786/14442955/b67074c2-003c-11e6-93b3-4dcc3bcab1c6.png)

**Comment by mammuth** [comment]
We had a PR un-justifying headlines. Probably this is caused by this one. What a pity we didn't notice.
