### ISSUE TITLE
Some polishing :)

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#379]
Speaking about the version currently hosted on https://beta.got.show
1. ~~In the footer~~
   - ~~About and Credits link to the about page. Remove the Credits link, leave the About.~~
2. In the about page
   - Please change the order of the Mentors list to:
     - ~~Guy Yachav~~
     - ~~Tatyana Goldberg~~
     - ~~Christian Dallago~~
     - ~~Dmitrii Nechaev~~
3. ~~In the characters page~~
   -  ~~Please change the order of the dropdown to:~~
     - ~~Popularity~~
     - ~~Name A to Z~~
     - ~~Name Z to A~~
     - ~~Chance of death~~
     - ~~Chance of survival~~
4. ~~On home and ranking, less on character and about pages:~~
   -  ~~There seems to be a lot of `padding` at the end of the content and before the footer, can this be fixed?~~

Thank you **very** much from my side, @goldbergtatyana and @gyachdav (**edit**: and @dmitry-n of course) we are very happy about your work :)

**Comment by goldbergtatyana** [comment]
thanks @sacdallago! There is one typo: in the mentors list Chris' name should go before my name please! Thanks

**Comment by jorjo1** [comment]
@goldbergtatyana that's the order in the JSON file we have :P So it was first-come-first-serve. All right, fix is coming

**Comment by yashha** [comment]
I do the sorting change dropdown change @jorjo1

**Comment by yashha** [comment]
Shell we rename "Death chance" to "Chance of death"? ^^ or did you mean "Death chance"?

**Comment by goldbergtatyana** [comment]
'Death chance' sounds better to me :)

**Comment by yashha** [comment]
@jorjo1 can this be closed?

**Comment by jorjo1** [comment]
Not yet

**Comment by yashha** [comment]
Now? ;)

**Comment by jorjo1** [comment]
#398 :checkered_flag:
