### ISSUE TITLE
Add Analytics Features

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#38]
We should probably add analytics where we can track how our visitors are behaving on the webapp?

Options:
- Google Analytics
- Piwik
- ...

**Comment by jorjo1** [comment]
@sacdallago should we use our personal emails or you would probably want to use Rostlab's email?

**Comment by sacdallago** [comment]
Google analytics please!

@jorjo1 This is part of a mutable configuration which shouldn't be saved on git ;) I will generate the ID and expect to have some config file where I just put the ID and domain info in and it will take care of putting this into the right places in the app. Ok? :)

**Comment by yashha** [comment]
#77

**Comment by gyachdav** [comment]
Can you give us access to analytics? Thanks

**Comment by sacdallago** [comment]
thx @yashha 

we are gonna put anyway another analytics code for production @gyachdav 
I have it read already and it's been running on the dummy got.show website!

Also, latest update: I got SSL working, we'll see if I can set it up again for the real thing.
