### ISSUE TITLE
Development freeze in 2 hours

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#397]
Hey guys, 

It is now time to announce a development freeze for the got.show website. 

You guys have done an incredible job reducing your issues list from >40 to about 15 minor importance issues and altogether shaping up the the website to look really cool, robust and professional.

Please take until **18:00CET** to clean up and wrap up. Finish the issues that are now affecting the way the website looks so by 18:00CET @sacdallago we can launch beta on got.show. We  @goldbergtatyana, @sacdallago and myself will also work to finish our outstanding items (stats page, predictors description).

Please confirm you got this message and lets launch today!

**Comment by jorjo1** [comment]
I got this message, will do anything possible to fix main issues till 17 CET

**Comment by yashha** [comment]
We need to start merging. :(

**Comment by sacdallago** [comment]
Now you can merge all PRs that are OK to be merged, the rest you please close. Once there are no PRs the site goes live

**Comment by mammuth** [comment]
Will join soon, I'm already into stopping my current work :+1:

**Comment by sacdallago** [comment]
:+1:

**Comment by jorjo1** [comment]
I just did not manage to do some improvements because of personal issues, I am sorry. If @sacdallago is okay with that I can do this overnight

**Comment by gyachdav** [comment]
You're asking to extend the freeze to tomorrow?

**Comment by mammuth** [comment]
<img width="1020" alt="screen shot 2016-04-11 at 22 35 09" src="https://cloud.githubusercontent.com/assets/3121306/14441565/ad55126e-0035-11e6-9b8e-45ebe22e3f06.png">

**Comment by jorjo1** [comment]
No, I am not asking for extension. The website is ready, but the things I would like to make even cooler will be post-release.

**Comment by sacdallago** [comment]
The _final_ version is up and running.
If @jorjo1 you want still to add some modifications, integrate this with the one PR of the landing pages tomorrow! Last PR ;)
Trust me, it's for you

**edit** up and running, I just need to change a few things here and there with nginx :D gimme like.. 10 minutes :D

**Comment by sacdallago** [comment]
Oh, and @yashha please tear down the heroku deployment :)

**Comment by gyachdav** [comment]
@sacdallago, sure this is the version we want in prodcution?
![screen shot 2016-04-11 at 5 07 01 pm](https://cloud.githubusercontent.com/assets/4074881/14442431/bb2bf516-0007-11e6-84d8-a3d530f5344f.png)

**Comment by sacdallago** [comment]
AAAnnnnnddddd last but not least, in that PR tomorrow:

# Please

# The

# Homepage!

That thing on the bottom

# 's

# uggghlleeyy

:joy:

**Comment by sacdallago** [comment]
@gyachdav that's what I got from develop :D but if you look up, I already mentioned it :D

**Comment by mammuth** [comment]
Btw, @sacdallago do you have a hook onto the staging branch here? Or maybe a dedicated branch? Would be a pity if you need to get hand on the server everytime we want to deploy a new version :wink:

**Comment by sacdallago** [comment]
I'll create a CRON job to pull from master every x days?

**Comment by gyachdav** [comment]
but now there's no access to the landing pages...

**Comment by sacdallago** [comment]
It's gonna come in tomorrow's one and only last PR, am I right? @mammuth @yashha @jorjo1

**Comment by mammuth** [comment]
:scream: You must be kidding :wink:  

_It's 2016 - the age of .show domains_, remember? Guess what, there are better solutions for CI than cronjobs :wink: 
https://help.github.com/articles/about-webhooks/
@kordianbruck and I wrote such a hook some time ago, supporting proper authentication with GitHub etc.:
https://github.com/kordianbruck/AutoUpdate

**Comment by mammuth** [comment]
> It's gonna come in tomorrow's one and only last PR, am I right?

Maybe I'm going for a last direct push to develop as well? :blush:

**Comment by gyachdav** [comment]
c'mon guys now I feel like I was locked out of the ice cream shop... pleas put in the links to the landing pages.

**Comment by sacdallago** [comment]
I know, I know... CRON job, 1 line, 5 minutes, your way, ? lines, ? minutes! I'm human, not smart

**Comment by sacdallago** [comment]
@gyachdav you are gonna get it! don't worry. Have faith! @mammuth ? As in: @mammuth tomorrow in the PR, PLEASE :D :D

**Comment by yashha** [comment]
https://got.show/jon-snow-is-not-dead.html
https://got.show/daenerys-targaryen.html
https://got.show/house-stark.html

**Comment by mammuth** [comment]
@gyachdav what exactly do you mean? 
Landing pages seem to be properly served:
<img width="1262" alt="screen shot 2016-04-11 at 23 11 03" src="https://cloud.githubusercontent.com/assets/3121306/14442609/fe60bf64-003a-11e6-8db3-04215b93fbd4.png">

**Comment by sacdallago** [comment]
He is talking about those uuuugghhlleeey lorem ipsum at the bottom in the home.. They should also point to the landing pages, one paragraph x landing page... just copy paste + read more link

**Comment by mammuth** [comment]
Right, we can do this whenever landing-pages are realy ready to be linked to: #404

**Comment by sacdallago** [comment]
**BEST, ISSUE NUMBER, EVVAH**
