### ISSUE TITLE
Most dangerous houses

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#399]
here is the list of the top 10 popular dangerous houses:

House Tully 0.948
House Clegane   0.899
House Velaryon  0.843
House Seaworth  0.833
House Nymeros   0.822
House Targaryen 0.819
House Oakheart  0.611
House Greyjoy   0.592
House Lannister 0.576
House Westerling    0.576

**Comment by mammuth** [comment]
I guess we only display the TOP5 since all other rankings are also only 5?

**Comment by gyachdav** [comment]
if this is really awkward showing more then 5 then how about collapsing the second set of 5 houses and giving the option to expand? there are just interesting houses from the 6th position onward. 

also please link the houses to their page in the wiki.
