### ISSUE TITLE
Don't commit on develop / use feature model / revert commits

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#4]
@mammuth  you commited on the develop branch (f86a9a13b0c197349cb8db5f145bae97ced7c683), this is not what you should do.

Please:
- [x] Revert your commit and bring develop back to the initial state ( b88954d50be0b3a707e57028ee2372f81567bd70 )
- [x] Open a branch for the feature you work on, branching off from develop
- [ ] If you are already done with your feature, open a pull request

We would like you to implement the feature model. If you don't know how this works, please have a look at https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow/ and the video in which I explain it https://youtu.be/twKtSfLcKxI?t=12m25s
# I need to see pull request to know: who did what

:dancer: hope this makes you understand why I do this :D

**Comment by mammuth** [comment]
_I need to see pull request to know: who did what_ makes me understand (I guess). 

However normally for binaries (if they need to be in the repo), this model doesn't make any sense according to my experience. 
No doubt, for code-features it's useful of course.

I'm curious: If you use PR's to see who did what - how are you guys dealing with PR's that contain commits from multiple persons?

**Comment by sacdallago** [comment]
@mammuth:
1. Usually one person works on one feature (per definition of the feature model), if two work on one it is usually an equal distribution or there's a clear leader
2. You can look at the commits associated to the pull request :) Much less, usually, then looking at an entire development branch, and 
3. Binaries are of no interest to me. I look at quality and extend of your JS :)

Also, PR give a very nice way to retrospectively look at the project. I am very caught up with giving live feedback to people now. When the seminar is gonna be over and I will have the final big picture, I can have a look at the whole development of the projects over PR and understand how you worked and who did what and why.

Hope this answered all of your questions.
