### ISSUE TITLE
Make Ranking page

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#40]
Details and main idea: 

Refers also to #59 
- [x] "Who dies next" Both most likely to die characters (1 vs. 1)
- [x] top 5/10 most likely to die next
- [x] top 5/10 loved characters
- [x] top 5/10 hated characters
- [x] top 5/10 survivors

**Comment by mammuth** [comment]
As stated here we probably not only rank the sentiments, but also the PLOD's (https://github.com/Rostlab/JS16_ProjectB_Group7/issues/5#issuecomment-198023478) (ProjectB needs to come up with visualization suggestions and support us here).

So maybe we should make two subpages and a DropDown-Menu?
_Rankings_
-- _Who dies next?_
-- _Who is loved most?_

**Comment by gyachdav** [comment]
- [ ] Top 5 next eliminated (only one algorithm (Group 6), “see more” (links to character-listing, sorted by PLOD))
- [ ] ~~Top 5 to survive - Group 6~~
- [ ] Top 5 most liked - Twitter
- [ ] Top 5 hated - Twitter
- [ ] Top 5 most dangerous house Group 6

**Comment by gyachdav** [comment]
For 2.0
- [ ] ~~Traveller (who travelled the most, pls include the map showing his path) C10~~

**Comment by mammuth** [comment]
@mina-zaki could you implement your function-calls to the page, to get rid of the dummy-data?

**Comment by jorjo1** [comment]
We'll collaborate on the design.

**Comment by mina-kleid** [comment]
Is this still relevant ?

**Comment by mammuth** [comment]
Yep, it is still relevant since we currently only show hardcoded dummy data. The integration of the sentiments & plods into the ranking-page is missing.

**Comment by mammuth** [comment]
ToDo:
- [x] missing: PLOD Top5 (there seems to be no function int the storer for that?)
- [x] houses: same here. are they changing at all? probably not? so we could at least hardcode them.

(PLOD "see more" will work, when the sorting is implemented in the characters-list )

**Comment by goldbergtatyana** [comment]
Hi @mammuth, both PLOD Top5 (please use table "PLOD for 20 Most Popular characters" from https://github.com/Rostlab/JS16_ProjectB_Group6/issues/66) and houses (https://github.com/Rostlab/JS16_ProjectB_Group6/commit/e1616a6e99120072a7c63faaf0609faeb4e5aab3, i still need to check if calculation ok though...) won't change anymore and can be hardcoded.

**Comment by goldbergtatyana** [comment]
Giving you green light @mammuth for using https://github.com/Rostlab/JS16_ProjectB_Group6/commit/e1616a6e99120072a7c63faaf0609faeb4e5aab3#diff-2ede64b7b72d3ec354d36ea21bec8cdb for the list of TOP 5 popular & dangerous houses

**Comment by goldbergtatyana** [comment]
Just to clarify:
In the table "PLOD for 20 Most Popular characters" from https://github.com/Rostlab/JS16_ProjectB_Group6/issues/66#, everyone with PLOD>0.5 is within the list of next eliminated, while everyone with PLOD<0.5 is within the list of survivors.

Survivors are:
PLOD Name
3.9 Sansa Stark
11.6    Jon Snow
16.6    Cersei Lannister
18.7    Mace Tyrell
28.9    Roose Bolton
41.4    Barristan Selmy

Next to die are:
PLOD Name
97.9    Tommen Baratheon
96.4    Stannis Baratheon
95.3    Daenerys Targaryen
91.8    Davos Seaworth
91.8    Petyr Baelish
74.1    Theon Greyjoy
71.1    Bran Stark
70.7    Tyrion Lannister
68.7    Samwell Tarly
68.5    Arya Stark
64.8    Margaery Tyrell
64.8    Jaime Lannister
61.3    Walder Frey
53.5    Varys

**Comment by mammuth** [comment]
ToDo: Survivors

**Comment by jcebel** [comment]
Hey, sorry to bother you guys. But I just looked at the ranking page and the switch for the different algorithms disappeared. Wasn't that the way to integrate both Twitter-applications?

**Comment by sacdallago** [comment]
@jonny3576 we decided to go for a mixed approach, since the two groups have a slightly different take on the data, instead of showing twice the same thing, we use a bit of the functionality of one group and bit of the functionality of the other one to make the whole think more interesting :)

**Comment by jcebel** [comment]
Ah ok :+1: I like that idea. If you guys need any support, feel free to ask!

**Comment by mammuth** [comment]
I think we can close this issue. The only thing left is probably some more beautiful design - we have an issue for that #298

**Comment by marcusnovotny** [comment]
Sorry that I reopen this, but we'll have to rephrase "Most loved" and "Most hated" into "Most positive mentions" and "Most negative mentions" since some popular characters ended up in the most hated column. Makes a lot more sense that way, because the tweets were from people worrying about them.

See our discussion over at #363 for more info. Thanks.
