### ISSUE TITLE
"Loading" in char page out of frame

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#408]
I think this has always to do with the not-justifying titles @mammuth

**Comment by jorjo1** [comment]
This needs to be fixed: 
h1, h2, **h3**, h4, h5, title {
    font-family: Cinzel Decorative,cursive;
  ~~*\*  text-align: left;**~~
}

**Comment by yashha** [comment]
No we wanted to have the main style like this
just make an .center class and center it manually
