### ISSUE TITLE
No left / right margin on Android Chrome 49

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectF#409]
![screenshot_2016-04-12-10-49-11](https://cloud.githubusercontent.com/assets/17390795/14454874/c4c72b50-009c-11e6-85e9-e4095106c295.png)

The page gets cut off at the sides, regardless of the way I tilt my Z3 Compact

**Comment by kajo404** [comment]
I was just about to make an issue about it :D 
Same on my Galaxy S5

![screenshot_2016-04-12-13-48-25](https://cloud.githubusercontent.com/assets/11276160/14459807/7091390e-00ba-11e6-8929-2b674d0c2b92.png)

**Comment by sacdallago** [comment]
Seems to be fixed (Tried on chrome mobile emulator)
