### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#41]
Create a 404-not found/allowed with a fancy design.

Subtask of #37

**Comment by sacdallago** [comment]
I love 404 pages! (Dead serious)
- http://hotdot.pro/en/404/
- http://bluegg.co.uk/404

**Comment by gyachdav** [comment]
you can use your dead jon snow background as our 404

**Comment by jorjo1** [comment]
Or Hodor. More like it, right. :wink:
