### ISSUE TITLE
Center PLOD character name

### ISSUE THREAD

**Issue by TheZoker** [Rostlab/JS16_ProjectF#412]
Current look:
![img_2016 04 12_19h02m05s_002_](https://cloud.githubusercontent.com/assets/1368405/14466910/1466dd4a-00d9-11e6-8974-11e2507abe2f.png)
Suggested look:
![img_2016 04 12_19h02m40s_003_](https://cloud.githubusercontent.com/assets/1368405/14466911/14672a5c-00d9-11e6-8158-f5eb19feba19.png)

Also the twitter sentiments header would need a padding or needs to be centered:
![img_2016 04 12_19h02m58s_004_](https://cloud.githubusercontent.com/assets/1368405/14466912/1467b2b0-00d9-11e6-84f2-22cc4cd24f82.png)

**Comment by yashha** [comment]
First issue is the same as #408
And second I'll do in a minute
