### ISSUE TITLE
Add Metadata to all views + SEO

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#42]
Subtask of #37

**Comment by sacdallago** [comment]
https://developers.facebook.com/docs/sharing/webmasters#markup

**Comment by sacdallago** [comment]
https://dev.twitter.com/cards/markup

**Comment by jorjo1** [comment]
@sacdallago Hi Christian, thanks for the links. But what we actually need is description, project title and some idea for the photo. I will craft the image, but I still need description of the project.. :hammer: :hourglass:

**Comment by sacdallago** [comment]
@jorjo1 didn't you have an static-pages representative :D use some pure geek imagination :star2: 

Project title on the other hand: **A Song of Ice and Data**

The domain where the site will be is (brace yourselves) [THIS FREAKING AWESOME GUY](http://got.show)

**Comment by mammuth** [comment]
Puh, hopefully HBO makes no trouble when we're using got.show :blush:

**Comment by yashha** [comment]
@Andrew094 <-- staticpages representative

**Comment by jorjo1** [comment]
http://schema.org/docs/gs.html

Testing tools:
https://dev.twitter.com/docs/cards/validation/validator
https://developers.facebook.com/tools/debug/
http://www.google.com/webmasters/tools/richsnippets
http://developers.pinterest.com/rich_pins/validator/

And also very important (SEO):
https://moz.com/blog/seo-cheat-sheet

:muscle:

**Comment by sacdallago** [comment]
Btw: https://www.facebook.com/aSongOfIceAndData
@Rostlab/js_cs_sose_2016_students please:
1. Like the page
2. Tell me who wants to be added as moderator/editor/admin

**Comment by mammuth** [comment]
Cool! :+1:
You can add me to the page if you still need some mods/admins - I'm used to
managing pages ;-)
(I wrote to the page on FB - so you know my account)

**Comment by jorjo1** [comment]
I can be a mod/admin too :monkey: .

Although, we think that the Facebook page should be named "A song of ice and data" just like in the URL because GoTShow is not self-explanatory. :question:

**Comment by yashha** [comment]
Me too :point_up:

**Comment by ghost** [comment]
I already asked for on facebook ;)
Still available. :P

**Comment by sacdallago** [comment]
I'll add you all, just write me a PM on the fb page.
Yeah, I would rename it, if only I found the DAMN setting somewhere.

EDIT: write me on fb with the email you have associated with it. I can't add you my link, name, or anything on that shit

EDIT 2: Nah. Was able to do it somehow. Fuck facebook

**Comment by jorjo1** [comment]
info/?tab=page_info is where you find and change page name :)

**Comment by sacdallago** [comment]
We also have a google page:
- https://plus.google.com/116097558064950719723

It can be also used to post videos on youtube! So, if you want access gimme your google credentials.

We have twitter:
- https://twitter.com/asoiad

Ask me for the password (it's a community effort, afterall :D )

Anything else? Close this?

**Comment by gyachdav** [comment]
@sacdallago you rock man!

**Comment by sacdallago** [comment]
@Andrew094 https://builtvisible.com/react-js-seo

**Comment by gyachdav** [comment]
Are all requirements from this and #151satisfied? can this be closed?

**Comment by gyachdav** [comment]
do not close until @marcusnovotny okays closing it

**Comment by marcusnovotny** [comment]
It's okay we'll track progress over at #151, @Andrew094 is assigned there too.
