### ISSUE TITLE
Should the header be fullscreen?

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#423]
![image](https://cloud.githubusercontent.com/assets/4728786/14502496/cd418838-01ab-11e6-91f2-9aa165abc3cc.png)
![image](https://cloud.githubusercontent.com/assets/4728786/14502482/b8b24772-01ab-11e6-8681-bd48fa5aec0a.png)

**Comment by jorjo1** [comment]
It **must** be actually, we are searching for the PR that causes this.

**Comment by mammuth** [comment]
I found it (https://github.com/Rostlab/JS16_ProjectF/commit/272c3ea1725645c9ddd3d8c24cd10e2527f7f605), it was @yashha who introduced this behaviour - so I hoped, he could answer exactly this question :stuck_out_tongue_winking_eye:

**Comment by sacdallago** [comment]
At a second glance, I don't mind it.
Keep it
