### ISSUE TITLE
Higher main-container padding on mobile

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#427]
iPhone5 Screensize:
<img width="355" alt="screen shot 2016-04-13 at 19 44 35" src="https://cloud.githubusercontent.com/assets/3121306/14503397/380d5cba-01b0-11e6-84bb-c288ad0ed640.png">

**Comment by mammuth** [comment]
This could be resolved, by setting the main-container padding-top to something higher, because the navbar is higher than on desktop.

**Comment by mammuth** [comment]
Actually since the missing padding is a problem on every page, we might just higher the padding on mobile (s. statistics page eg.)

**Comment by mammuth** [comment]
Whoever is doing this: It also happens with tablets, so test that as well.

**Comment by jorjo1** [comment]
Title -> We simply make the font of the title smaller. :)
