### ISSUE TITLE
Spring cleaning

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#435]
I deleted almost all branches :dancer: 
Be careful what you are working in and if it exists still on remote. (otherwise just push it to remote as a new branch)

There are a **few** branches that survive. Please review if they are necessary and kill them otherwise!

If I disrupted someone's flow I'm sorry, but this needed to be done :P

**EDIT**: There's **one** that survived :D @yashha The rest are just commodity branches

**Comment by yashha** [comment]
You can let the last one live, it is not harming anybody ;)

**Comment by jorjo1** [comment]
@sacdallago when are you transferring the rep to the github.com/got-show ?

**Comment by sacdallago** [comment]
That should be made with more than just one hand.. I'd need one person from every group (at least: sentiments, api, you and map) to do that, just to make sure nothing breaks. I don't think it is a good idea to do this now, with traffic on the 2,5k average per day and PRs going on.. in two weeks, maybe

**Comment by yashha** [comment]
Can this be closed?

**Comment by sacdallago** [comment]
Yeah but it's becoming a problem again :D will spring clean again once most/all PRs are closed
