### ISSUE TITLE
Statistics page

### ISSUE THREAD

**Issue by goldbergtatyana** [Rostlab/JS16_ProjectF#441]
First, I would say we need a "Read more" link in the GoT STATS section of the homepage. The link should lead to https://got.show/statistics. I would also looove having the image of GoT STATS from the homepage being an active link and leading to https://got.show/statistics.

On the statistics page itself the-still-present drawbacks are:
- the font color of the x-axis labels in Figure 1 is not light gray as all other text in that figure
- all figures and their descriptions are not centered, but should be --> would make the page more beautiful :heart_eyes:

**Comment by gyachdav** [comment]
Guys please take care of this ASAP. We get mad traffic at the moment >150 ppl real time and not Hanover the link there is a big minus. 

@sacdallago please make sure this is complete by EOD thanks
