### ISSUE TITLE
Only one Twitter Graph on Homepage gets resized

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectF#445]
Only the right graph gets resized, the left one is simply overshadowed. 

The function `d3.select(window).on('resize', function(){ . . . });` has to resize both charts

Extreme example:
![resize error](https://cloud.githubusercontent.com/assets/17390795/14560490/7565d5cc-0310-11e6-901f-09e7bb313550.png)

**Comment by yashha** [comment]
```
var chart1 = new characterChart(d3.select("#chart1"), "/d4/csv/" + name1 + ".csv"); /*eslint no-undef:0*/
d3.select(window).on('resize', chart1.resize);/*eslint no-undef:0*/
var chart2 = new characterChart(d3.select("#chart2"), "/d4/csv/" + name2 + ".csv"); /*eslint no-undef:0*/
d3.select(window).on('resize', chart2.resize);/*eslint no-undef:0*/
```

**Comment by marcusnovotny** [comment]
That won't work because you can only specify one dom event handler per event. Make it

`d3.select(window).on('resize', function(){
chart1.resize; 
chart2.resize;}`

**Comment by yashha** [comment]
Thanks, I'll try it! :)

**Comment by marcusnovotny** [comment]
Tell me if it's not working, I had it running once already :smile:
