### ISSUE TITLE
Site is broken

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#448]
https://www.got.show/

**Comment by yashha** [comment]
It seems like the api is down.

**Comment by gyachdav** [comment]
I got 504 when trying the API 

https://api.got.show/api/characters/

**Comment by yashha** [comment]
Api running again! :)

**Comment by gyachdav** [comment]
@sacdallago fixed it

**Comment by yashha** [comment]
The font is blocked.
Maybe you have to change something on ngix.
Edit: http://stackoverflow.com/questions/25577981/font-from-origin-has-been-blocked-from-loading-by-cross-origin-resource-sharing

**Comment by sacdallago** [comment]
@yashha so this is an issue I still need to fix?

**Comment by yashha** [comment]
Yes at the moment I have a comic sans like font on the website ;)
![image](https://cloud.githubusercontent.com/assets/4728786/14577386/8d21f64c-0373-11e6-9aa2-9554d77d9888.png)

**Comment by yashha** [comment]
![image](https://cloud.githubusercontent.com/assets/4728786/14577394/a7ec8686-0373-11e6-9f6d-00dd4f120cae.png)

**Comment by sacdallago** [comment]
That's so not happening to me. Try incognito?

**Comment by yashha** [comment]
Thanks :)
