### ISSUE TITLE
Twitter panels on mobile

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#459]
Please see feedback from this mailing list http://www.meetup.com/ny-tech/messages/78486305/

".... The only thing that would help me enjoy it more is if the two Twitter sentiment graphs were stacked vertically instead of horizontally, because they're too smooshed together on mobile.."

Can we make (on mobile only) the two panels stack and have the character name on top of each twitter panel?

**Comment by marcusnovotny** [comment]
Thanks for the fix, works great!
