### ISSUE TITLE
Create custom preloading animation

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#46]
I decided to make a page preloading animation because it will look better while loading page content.

Example: https://ihatetomatoes.net/demos/css3-preloader-transition/

**Comment by yashha** [comment]
Other design maybe, and the loading time is very low.

**Comment by jorjo1** [comment]
Yes, I don't mean to take precious user time when the page is fully loaded. We are aiming of doing this in a not annoying way, but still thematically - something like a ~~sword/shield/opening doors~~... It's still only an idea, so anyone should feel free to contribute on this one.

**Comment by sacdallago** [comment]
@yashha is right about intrusive loadings. Usually what people do nowadays is a little 3px bar on top of the page which loads from left to right... Like the one I implemented on http://got.show but on top and full page with

**Comment by jorjo1** [comment]
#100. I close this too.
