### ISSUE TITLE
Include rostlab logo in the footer

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#460]
Professor Rost asked us to put the rostlab logo at the footer of the page next to TUM logo and link to the group's webpage. You will find the asset on the rostlab.org site.  

This is top priority item and should be done ASAP. Thanks!

**Comment by sacdallago** [comment]
@jorjo1 @mammuth @yashha Please can someone take care of this so that we have it by tonight? Press Release matters :)

**Comment by jorjo1** [comment]
Edit: Doin' it.

**Comment by goldbergtatyana** [comment]
You got the logo, @jorjo1 ?

Bitmap graphic https://rostlab.org/~goldberg/Logo_A4.png
Vector graphic https://rostlab.org/~goldberg/Logo_A4.pdf
Or as a square https://rostlab.org/~goldberg/Logo_squared.png

**Comment by jorjo1** [comment]
Thank you. But there is no more TUM logo there, we only have TUM and Rostlab links in the footer. Shall I put the TUM logo also again?

**Comment by yashha** [comment]
There is a TUM logo atm.
![image](https://cloud.githubusercontent.com/assets/4728786/14588891/46c13312-04d5-11e6-97d9-52d7e3e96b1e.png)

**Comment by jorjo1** [comment]
Oh sorry. It seems an extension for my browser has blocked some sources.. And the logo was hotlinked `https://www.schueler.tum.de/fileadmin/tum/org/tum-logo.png` :see_no_evil:

**Comment by sacdallago** [comment]
Nice Job @jorjo1 !

**Comment by jorjo1** [comment]
Thank you sir :tophat:

**Comment by jorjo1** [comment]
@yashha COMIC SANS?!?!!?! Did you block google fonts?

**Comment by goldbergtatyana** [comment]
no comic sans for me (though i see it sometimes when the page takes ages to load on firefox when there are too many other tabs open at the same time). and yeah the logos look beautiful! the feature of coloring them upon mouse hover is :+1: :+1:

**Comment by sacdallago** [comment]
@jorjo1 also @yashha had this problem yesterday.. It's starting to worry me :D just go incognito 😎

**Comment by jorjo1** [comment]
I didn't have the problem, but it happens when you block many sources like google fonts etc (or your connection works the funny way around) :P
