### ISSUE TITLE
got.show in the news

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectF#464]
We should create a Clipping page for all news articles.

E.g.: http://derstandard.at/2000035197733/Mathematiker-berechnen-wer-in-Game-of-Thrones-als-naechstes-stirbt?ref=rss

**Comment by gyachdav** [comment]
design suggestions?

**Comment by yashha** [comment]
http://stevinho.justnetwork.eu/2016/04/19/got-wer-stirbt-als-naechstes/

**Comment by mammuth** [comment]
http://thenextweb.com/shareables/2016/04/19/app-uses-machine-learning-guess-will-die-next-game-thrones/

**Comment by yashha** [comment]
http://www.rollingstone.de/wer-stirbt-als-naechster-bei-game-of-thrones-studie-bietet-die-antwort-1009929/
http://www.luzernerzeitung.ch/nachrichten/panorama/panorama-sda/Mathematiker-sehen-Game-of-Thrones-voraus;art46441,720518
https://idw-online.de/en/news649805
http://www.cnet.com/news/algorithm-predicts-fans-have-not-seen-the-last-of-a-certain-game-of-thrones-character/

**Comment by gyachdav** [comment]
http://www.cnet.com/news/algorithm-predicts-fans-have-not-seen-the-last-of-a-certain-game-of-thrones-character/

**Comment by yashha** [comment]
http://de.engadget.com/2016/04/19/a-song-of-ice-and-data-algorithmus-will-nachste-game-of-thrones/

**Comment by gyachdav** [comment]
move this conversation to the google group please. let the others enjoy it too!

**Comment by gyachdav** [comment]
@mammuth @yashha @jorjo1  we need one of you to take care of the twitter Issue asap! @marcusnovotny just opened an issue about changing the link on the site to the new twitter account

**Comment by gyachdav** [comment]
https://github.com/Rostlab/JS16_ProjectF/issues/465

**Comment by gyachdav** [comment]
@sacdallago is waiting for you to do this asap and he is ready to pull to production.

**Comment by gyachdav** [comment]
background: twitter is exploding >70 from twitter alone and we dont wanna lost followers

**Comment by gyachdav** [comment]
ill remove all the unrelated comments from this issue now. you guys can resume your link postings. BUT please also start a link war on the g-groups 😄

**Comment by yashha** [comment]
https://groups.google.com/forum/#!topic/javascript-technology-2016/KpQHvwGb84g
@kordianbruck Do you mean a page on our Website?

**Comment by kordianbruck** [comment]
@yashha yes, it would be great to collect these publicly on the website as well.

**Comment by sacdallago** [comment]
@kordianbruck is right. We'll also take all of the links on the link-wars page on ggroups and generate PDFs of them.. Who knows how much all of them are gonna stay up!... This stuff builds CV!

**Comment by theocheslerean** [comment]
Perhaps it would be interesting to add some kind of comments section on the website. Facebook comments or smth like that

**Comment by mammuth** [comment]
There exists an dedicated issue for page comments.

**Comment by mammuth** [comment]
Closing in favor of the above issue.
