### ISSUE TITLE
Reference new twitter account @GotJstech

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectF#465]
Hey folks,

we had to switch twitter accounts from @ asoiad to @ GotJstech

Please reference the new account on the homepage asap so we can start using it.

**Comment by sacdallago** [comment]
PLEASE @jorjo1 @mammuth @yashha do it now so I can go home and rebundle we have 200ppl on the page

Sorry, am in car

**Comment by marcusnovotny** [comment]
@mammuth Hijacking this, do you have a nicer image for the twitter header? Current one is terribly pixelated

https://twitter.com/GotJSTech

**Comment by mammuth** [comment]
@sacdallago who did the win or die header graphic? 

Maybe this person could export it in larger size. At least the red/black background image is pretty large, so the small size probably came by adding the text.

**Comment by sacdallago** [comment]
@jorjo1 wasn't it you?
