### ISSUE TITLE
Generate a sitemap

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectF#469]
We need to generate a sitemap for Google Analytics. One way to do it is to use something like http://botmap.io/, which is an example of a service that allows to generate sitemaps for js-heavy websites (instructions are on the front page). Anything else can be used as long as it works.

**Comment by mammuth** [comment]
We have a sitemap (see https://got.show/sitemap.xml). 
Why do we need something different _for Google Analyitcs_ or what do we need to change at the current sitemap?

**Comment by ghost** [comment]
Just because I overlooked sitemap.xml, that's all. It will work just fine.

**Comment by mammuth** [comment]
I hope so - I put some decent effort in implementing the sitemap generator, which, btw, also has all characters listed, with their priority set accordingly to their plod :blush:

**Comment by ghost** [comment]
Can I see this generator source code, btw? Oh, and using PLOD as priority leads to priority set to NaN for some chars. Google Search Console doesn't like that.

**Comment by mammuth** [comment]
As stated in the other issue (#471):

> Can be fixed by adding an _or_ statement to the priority assignment here: https://github.com/Rostlab/JS16_ProjectF/blob/develop/sitemap-generator/sitemap-generator.js#L14
