### ISSUE TITLE
Redirect www subdomain

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#470]
I mentioned this somewhere sometime ago, that running both hosts (www.got.show and got.show) doesn't make any sense.

Now even GA is complaining:
![analytics-hosts](https://cloud.githubusercontent.com/assets/3121306/14679188/1d82cbf0-0719-11e6-9752-b6df175af9dc.png)
So let's do this 301 :wink:

**Comment by sacdallago** [comment]
I will fix this tomorrow during the "fake" coding session! Thank you very much for pointing out @mammuth

**Comment by yashha** [comment]
Status? ;)

**Comment by sacdallago** [comment]
It's a one line change, will do at some stage
