### ISSUE TITLE
Fix NaN values in the sitemap

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectF#471]
Google tools complain about our current sitemap:

Invalid tag value - This XML tag has an invalid value. Please fix it and resubmit - 143  occurences - Parent tag: url, Tag: priority, Value: NaN

**Comment by mammuth** [comment]
Can be fixed by adding an _or_ statement to the priority assignment here: https://github.com/Rostlab/JS16_ProjectF/blob/develop/sitemap-generator/sitemap-generator.js#L14

I'm not with my private laptop until late evening; so if someone wants to fix this earlier, he can go for it :blush:
