### ISSUE TITLE
Legal mattes

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#482]
Finally we got to a compromise with the legal office. The following needs to be worked on urgently and concluded ASAP.
I appreciate your effort very much. As you might have understood, I do everything I can to stay on top, but I'm extremely slowed down by the organizational matters.
1. Please for
   - all the images shown on the front page `/`
   - The image on the top (header)
   
   attribute on the bottom of the image (inside the image, **EXACTLY THIS TEXT**!):

> © 2016 Home Box Office, Inc. / Sky All rights reserved.
1. Use this as the Impressum for the TUM part: http://www.forschung-garching.tum.de/index.php?id=11
   For **Inhaltlich verantwortlich** put ( @gyachdav confirm pls. This is "Content responsible" )
   Dr. Guy Yachdav
   Arcisstr. 19
   80333 München
   E-Mail: gyachdav@rostlab.org
2. On the top of the page, the very top: the entire body should be shifted down about 20px. The TUM logo should appear in the middle, and on it's right **Technische Universität München**. There are specifications for: Font-size, Font-type, Background color and PNG image to be used. Something like this: http://www.tum.de/ but maybe the div make it smaller? @jorjo1 the .css expert can handle this, I guess.

Thank you so, so much!

**Comment by sacdallago** [comment]
Email we just got:

> Dear all,
> 
> since the changes in the disclaimer are really minor changes, but might have a larger impact, please do these changes as soon as possible.
> 
> Also adding a grey bar at the top which carries the TUM logo and the name plus a small grey or white line to separate it from the rest should be a thing of minutes. Please find a suggestion in the attachment. I chose RGB 105/105/105 as the lighter grey. White was too strong, 31/49 was too weak.
> 
> Kind regards
> 
> Andreas

![grey_bar](https://cloud.githubusercontent.com/assets/6240943/14739285/e3c168da-0886-11e6-8a10-7e4f63884d92.jpg)

@mammuth @yashha @jorjo1 or anyone in the @Rostlab/js_cs_sose_2016_students please implement these changes ASAP, me @goldbergtatyana and @gyachdav are busy making you famous :P

**Comment by mammuth** [comment]
I'm without my laptop. @yashha, @jorjo1?

**Comment by gyachdav** [comment]
Guys please treat any request coming from TUM admins as real emergency i.e. the turnaround time need to be immediate. Whoever sees this first and capable of taking care of it, see this through from beginning to end (including self merge, you got my approval)

**Comment by goldbergtatyana** [comment]
@mammuth @yashha @jorjo Andreas Batternberg (who is being a great help for all possible matters) that this request is a super urgent one. Please please take care of the disclaimer and the TUM logo as soon as you can. Thanks

**Comment by yashha** [comment]
I haven't access to my laptop before 7 o'clock, sry

**Comment by jorjo1** [comment]
I GOT MY LAPTOP. I am here to work!

**Comment by jorjo1** [comment]
#490 I have been so busy these days, I can only work in the pauses. :D I will get to the other images' sources today too.

**Comment by yashha** [comment]
Are you working on it? I have time now. I can't reach you.

**Comment by yashha** [comment]
How is this? I don't like it that much, but when we have to do it.
![image](https://cloud.githubusercontent.com/assets/4728786/14752027/41a3f10c-08cd-11e6-9712-84636be39373.png)

**Comment by theocheslerean** [comment]
Can you make it gray? to blend in with the background of the actual website. Or is this blue text on white background standard?

**Comment by yashha** [comment]
> Also adding a grey bar at the top which carries the TUM logo and the name plus a small grey or white line to separate it from the rest should be a thing of minutes

grey is ok i think

**Comment by jorjo1** [comment]
@yashha pls tell me if you merged it already :D The issues that are referring to this header and TUM logo are numerous and I got confused xD

**Comment by yashha** [comment]
Should it say "Liability notice" ?
![image](https://cloud.githubusercontent.com/assets/4728786/14868051/d2ec284e-0ccb-11e6-892d-9a806511bc50.png)

**Comment by gyachdav** [comment]
Yup
