### ISSUE TITLE
Our twitter share buttons are broken?

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#493]
https://twitter.com/intent/tweet?text=I%20hate%20Grey%20Worm&url=https%3A%2F%2Fgot.show%2F&via=asoiad&original_referer=

From the ranking page.. it simply shows me a message "This page does not exist" (Twitter). wtf?

**Comment by sacdallago** [comment]
Please @jorjo1 change `via=asoiad` to `via=gotjstech`in all occurrences!! :

https://twitter.com/intent/tweet?text=I%20hate%20Grey%20Worm&url=https%3A%2F%2Fgot.show%2F&via=gotjstech&original_referer=

**Comment by gyachdav** [comment]
merged, can be closed.
