### ISSUE TITLE
List of characters ordered by PLOD not loading / All chars on the startpage with 0%

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectF#498]
See title ;)

https://www.got.show/characters/?search=&page=1&sort=plod&order=-1

Tested it with various browsers.

**Comment by sacdallago** [comment]
We are experiencing EXTREMELY high traffic. Check back tonight/tomorrow and say if this is still the case

Even better, come tomorrow to my office @Adiolis (in the morning)
