### ISSUE TITLE
EMERGENCY 

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#499]
EMERGENCY: We need someone from project F right now to post a message on the site that due to heavy traffic we are not showing predictions properly. This is an emergency and should be acted on right now.  Please confirm you're on it.

**Comment by Emiliyana** [comment]
If you want you can use my post suggestion, don't know if you saw it.

Due to heavy traffic we are currently not showing predictions properly. Our
investigation shows that a hacker called GRRM might be behind it, trying to
kill our algorithm

**Comment by gyachdav** [comment]
Put on FB and Twitter right now. Thanks!

**Comment by mammuth** [comment]
<img width="1680" alt="screen shot 2016-04-25 at 16 37 51" src="https://cloud.githubusercontent.com/assets/3121306/14787635/850c857e-0b04-11e6-9a43-bfaa8ca84363.png">

Like this?

**Comment by gyachdav** [comment]
yes good. please merge. Chris please pull!

**Comment by mammuth** [comment]
The warning-top-bar is in develop via https://github.com/Rostlab/JS16_ProjectF/commit/17a0336773bef70a4676ed252d4dbc19c1226f96

@sacdallago you can pull/deploy.

**Comment by yashha** [comment]
Whats up with the predictions, what happend?

**Comment by yashha** [comment]
API down? @sacdallago 
https://api.got.show/api/characters

**Comment by sacdallago** [comment]
Not at all @yashha just SO MANY REQUESTS!

**Comment by sacdallago** [comment]
Closing this as I'm handling it differently. Unmerge the topbar please

**Comment by mammuth** [comment]
Reverted via https://github.com/Rostlab/JS16_ProjectF/commit/ac11b832d5f6bc946d12aeff7c1c37a7b8d39fb6
