### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#50]
This will be needed in order to establish a connection with a service like:
- Google Analytics
- Twitter API
- ...

Subtask of #37

**Comment by mammuth** [comment]
More settings:
- Database host (for switching bruck-server with localhost-db-server)

**Comment by yashha** [comment]
More: https://github.com/Rostlab/JS16_ProjectD_Group5/blob/documentation/README.md
