### ISSUE TITLE
Episodes recap

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#500]
For the next 10 weeks we will publish an episode recap blog entry. 

The text will be published to the same file https://github.com/Rostlab/JS16_ProjectF/blob/episode-recap/static/episodes-recap and each week we will update the file with new contents. 

Please try to see if there is a way to separate the style from the contents (possibly build as a component?)

We also messed around with this for tooo long so I need someone to integrate this asap. This should've been out yesterday (my fault), so would be great if can be published asap. 

Thanks

**Comment by gyachdav** [comment]
@jorjo1 @yashha @mammuth where does this stand? we need this up asap! 
Please post questions if you dont understand what needs to be done but we really need this to be live.

**Comment by yashha** [comment]
I'm on it now.

**Comment by sacdallago** [comment]
1. Image is still to high
2. ~~[**THE LINK IS BROKEN**](https://got.show/episode-recap)~~

@gyachdav @yashha 

**EDIT**
2. was fixed with https://github.com/Rostlab/JS16_ProjectF/commit/a752e78ef2921770f109f8f883c176e94f0a038c
