### ISSUE TITLE
Sponsor logo mockup

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#509]
@mammuth @jorjo1 can you please design a quick mockup of what will a sponsor's logo look on the site ?

Maybe have two mockups one for the top (perhaps in the Navi or instead of the crowd funding banner) and another for the footer. 

I need this asap unfortunately so I can show potential sponsors that may fund our Lux trip.

**Comment by jorjo1** [comment]
![image](https://cloud.githubusercontent.com/assets/2246472/15073090/ec07383c-1397-11e6-815b-7c1293ce7549.png)
![image](https://cloud.githubusercontent.com/assets/2246472/15073095/efe6c922-1397-11e6-9955-4978f6961185.png)

**Comment by jorjo1** [comment]
![image](https://cloud.githubusercontent.com/assets/2246472/15073189/76d9ae68-1398-11e6-8111-c0eb3bbaba79.png)
![image](https://cloud.githubusercontent.com/assets/2246472/15073196/7a4752ee-1398-11e6-8a38-6292eddf012b.png)

**Comment by sacdallago** [comment]
Man this would have been cool
