### ISSUE TITLE
Add node multicore support

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#51]
https://nodejs.org/api/cluster.html

**Comment by sacdallago** [comment]
This is a brilliant idea and very easy to implement as long as you pay attention to what code to include in the workers and what to include in the master.
1. **Workers with little code are happy workers! :)**
2. **The master doesn't need to service anything**

Just as a small example, this is what I did last week: https://github.com/sacdallago/pssh/blob/master/index.js#L14

Notice the if/else

**Comment by yashha** [comment]
It is done by @sacdallago but not on github.
Do you wanna share your setup here?
You could put it in the repo wiki or push some config files.

Or is it to specific?
