### ISSUE TITLE
Map design issue

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#510]
![image](https://cloud.githubusercontent.com/assets/4728786/14992762/d824d7b6-1167-11e6-8240-f9aee7aaa1f3.png)

caused by #508

The font is an issue on my side ;)

**Comment by yashha** [comment]
![image](https://cloud.githubusercontent.com/assets/4728786/14996010/0891f112-1178-11e6-8455-e19dd8132aa5.png)

**Comment by sacdallago** [comment]
Cool! :D Hadn't noticed...
The donate button is gonna go in about a week, so I guess you shouldn't put too much effort into this! :) It's gonna be solved in a week anyway by just removing that div :)

**Comment by yashha** [comment]
Well too late and I could let I be like this.
The map is currently not useable.

**Comment by jorjo1** [comment]
Well Im on it now

**Comment by yashha** [comment]
Its already fixed, sry
