### ISSUE TITLE
Should there be some text?

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#517]
![image](https://cloud.githubusercontent.com/assets/4728786/15057976/f2f32cba-1319-11e6-84b8-54b6bb6e2a89.png)
https://www.got.show/episodes-recap

**Comment by gyachdav** [comment]
Yup this link should follow 

https://www.youtube.com/watch?v=rOMk5GWvlks

somehow it got dropped during the conversion

**Comment by yashha** [comment]
Oh I didn't see that it is a link, nvm ;)
