### ISSUE TITLE
Invalid tag value error sitemap

### ISSUE THREAD

**Issue by stingmad** [Rostlab/JS16_ProjectF#529]
My sitemap is creating issue and hence causing alot of problem 

here is my site sitemap 

http://www.hulkusc.com/sitemap.xml  thats the main sitemap

and within that site map http://www.hulkusc.com/sitemap-pt-post-2012-08.xml

thats what is creating problem and giving errors on 3 blog post urls

Error would show it shows value 29.8 mean 2980  and 22.7 mean 2280

But I have tried to set the priority now to 0.2 to 0.5 maximum but still error keeps coming back

I have tried to see the priority to 0.2 to 0.5 for blog posts  that and disabled automatically priority setting. I have submitted new sitemap three times but its coming back with same error. Please see the snapshot of error

Any help would be a great  relief.
<img width="1280" alt="screen shot 2017-03-09 at 14 47 52" src="https://cloud.githubusercontent.com/assets/26311759/23770186/07f93e78-050a-11e7-93f0-4ccbd7f67604.png">
<img width="1171" alt="screen shot 2017-03-09 at 13 35 06" src="https://cloud.githubusercontent.com/assets/26311759/23770197/10f6b5aa-050a-11e7-84e2-13e26597e9cd.png">

**Comment by stingmad** [comment]
I have submitted site map 4 times but same problem keep coming  I have no idea what is the issue

**Comment by sacdallago** [comment]
????? You sure you wrote to the right people? This has nothing to do with this project, I fear!
