### ISSUE TITLE
Router: highlight navigation for parent pages

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectF#54]
Navigation and routing are doing fine, but we just have to fix this when we address to a e.g. characters/:id
![image](https://cloud.githubusercontent.com/assets/2246472/13890496/06f5a858-ed4c-11e5-9b20-f22e7e0b3929.png)

![image](https://cloud.githubusercontent.com/assets/2246472/13890558/5e6eaf30-ed4c-11e5-8a13-574d1fe3f2fd.png)

**Comment by mammuth** [comment]
Yep, I thought about this aswell when I implemented the highlighting.

In non react apps my approach might be to just add the "active" class to
the "characters" menu item when you're at a characters detail page.

Any ideas how to do it nicely in our setup?

**Comment by jorjo1** [comment]
This is what I would do too, but I am waiting for @yashha to say his opinion, because he set up the routing. If it is not possible, I will do it with "active"-class.

**Comment by jorjo1** [comment]
Here is also a bug, I am just organizing stuff we should probably debug at some time.

![image](https://cloud.githubusercontent.com/assets/2246472/13895942/b1646d04-ed7b-11e5-99f2-4824c444fe80.png)
