### ISSUE TITLE
Messed up merge

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#6]
Hey guys,
how can I revert my merge and make a pull request.
Is says "There isn’t anything to compare."
Or was it ok to merge, when we said we will use my code?

**Comment by mammuth** [comment]
Just FYI:
I'm not sure whether github offers an option to revert a whole PR. 

Since some years ago git is capable of reverting a range of commits at once:
git revert OLDER_COMMIT^..NEWER_COMMIT

**Comment by yashha** [comment]
Fixed
