### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#65]
We have to collect here who _externals_ have to be attributed:
- ~~Project Member~~
- ~~Tutors~~
- [MediaWiki](http://gameofthrones.wikia.com/)
- [Westeros Wiki](http://awoiaf.westeros.org/)
- [404img](http://vignette4.wikia.nocookie.net/hieloyfuego/images/4/43/Hodor_HBO.jpg/revision/latest?cb=20130815031401)

@Andrew094 Your are responsible for static content don't you?

**Comment by jorjo1** [comment]
I assume we are just posting every single source we have used. I have used for now this picture
http://vignette4.wikia.nocookie.net/hieloyfuego/images/4/43/Hodor_HBO.jpg/revision/latest?cb=20130815031401

**Comment by Andrew094** [comment]
yes, thank your for opening the issue. Everything that should appear on the attributions on the about page, can be listed here.

**Comment by gyachdav** [comment]
text for attributions page is available here 

https://docs.google.com/document/d/1ELG34L1PV-UbLVsIJFMuxaiaZrgCR25UleHF2OHHUls/edit?usp=sharing

@Rostlab/js_cs_sose_2016_students  in case you used a source that is not in the table please add this in by April 5th  at the latest

**Comment by gyachdav** [comment]
Add to attribution page:
- [x] The A Song of Ice and Fire setting is Copyright © George R.R. Martin.
- [x] Game of Thrones TM and copyright HBO.

**Comment by jorjo1** [comment]
#381
