### ISSUE TITLE
Characters-Listing: Pagination

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#73]
Loading almost 2K characters is nonsense and takes a lot of time :-1: 

@mina-zaki for the logic part, @yashha for the represnation :kissing_heart:

**Comment by mina-kleid** [comment]
exactly, i was fighting with project A over it. 
https://github.com/Rostlab/JS16_ProjectA/issues/89

**Comment by sacdallago** [comment]
I don't recall exactly how the calls are implemented, but if the images are separated from the soft data, even loading 2K entries shouldn't take > than 3 seconds. I discussed [here](https://github.com/Rostlab/JS16_ProjectF/issues/59#issuecomment-198806107) how you could avoid delays

**Comment by gyachdav** [comment]
Sorry but project A has nothing to do with the pagination. They serve data not representation. Representation is your territory.  

What you should be doing here is create the logic that would tell you how many characters you can fit in one page. Let's say it's 20. Then you find out what sorting scheme you're using. Let's say it's alphabetical ascending. Then you check what filtering is used. Let's say it's female only. Now all you need to do is get the first 20 female chars names that are in your alphabetically sorted list of characters for the first page. The next 20 for the 2nd page and so on. The sorted and filtered list A can give you. All you need to do is keep track what page you're in, request the right list and images, and then render them nicely into the page. 

Just remember separation of concerns and you'll be fine ;)
