### ISSUE TITLE
Mobile: Close menu on item selection 

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#74]
Right now:
- open toggle menu on the top right on a phone
- select another page like about
  The target page will load, but the navigation drop down stays "open"  and overlays the content

Should be:
- navigation should toggle invisible after selecting a page

**Comment by jorjo1** [comment]
Also: set header z-index so that it's not overlayed by the page content 

:+1: ready

**Comment by sacdallago** [comment]
I also submitted an issue to **C10** to see if they can implement something similar for the right bar on the map. I know there's another issue somewhere in your repo discussing something similar, so: heads up

**Comment by mammuth** [comment]
It's better now by https://github.com/Rostlab/JS16_ProjectF/pull/292/commits/9375603474f8dbfb55c34d30a6782fda1da74cbe
