### ISSUE TITLE
Sorting, Filtering

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#78]
SortBy
- Name
- Populatity?
- **PLOD**

Filter by 
- House
- Gender

**Comment by mina-kleid** [comment]
getCharacters: function(page, sort, filter) 
sort = {field: Constants.SORT_FIELD_NAME, type: Constants.SORT_TYPE_ASC};
filter = {field: Constants.FILTER_FIELD_NAME ,value: "LyRI"};

**Comment by jorjo1** [comment]
I am not opening a new issue for that, but @mina-zaki please take this into account:
In favor of #59 we should add a search-field where names are autocomplete.

**Comment by mammuth** [comment]
Closing in favor of #99 

(Also autocomplete is probably not needed because we have instant feedback / filtering :sunglasses: )
