### ISSUE TITLE
Twitter Live-Tweets on all(?) pages

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#79]
By @sacdallago :
_"Implement a twitter widget/live feed at the bottom of the page / at the bottom of every page (even the home, with search query gotshow) :D you style a widget via the [twitter widget page](https://twitter.com/settings/widgets) and then in every page you just need to make sure you change the search term, aka:"_

```
<a class="twitter-timeline" href="https://twitter.com/search?q=got" data-widget-id="711494936588390400">Got live feed</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

```

_"Where you see got you change it to your URL-ENCODED search term ("Some Name" --> "Some%20Name" or "Some+Name" depending on what twitter wants)"_

So on character-detail pages add the character-name to the search query, use gotshow on the other pages.

**Comment by jorjo1** [comment]
I had this also in mind, thanks for the reminder ^^

**Comment by gyachdav** [comment]
Cool! But I think that having Thai on the home page is enough. No need to saddle the inside pages with too much unrelated info.

**Comment by gyachdav** [comment]
Honestly this doesn't look good and im not even sure why it's there. What do we get from distracting our users with a feed of tweets? [#toomanywidgets](https://twitter.com/hashtag/toomanywidgets?src=hash)

I vote to remove this all together.

**Comment by yashha** [comment]
I don't like it too, especially it's not mobile friendly.
We could put it in sth. like a sidebar on big desktops but not in middle of the page and not on mobile devices.

**Comment by sacdallago** [comment]
Well. Life is about mistakes and I made yet another one. Sorry for this guy's, if you think it has to go, let it go. :(

**Comment by gyachdav** [comment]
was this removed?

**Comment by gyachdav** [comment]
@jorjo1  please remove this. really burns my eyes :stuck_out_tongue_closed_eyes:

**Comment by sacdallago** [comment]
![](http://vignette2.wikia.nocookie.net/adventuretimewithfinnandjake/images/2/2b/Apply_cold_water_to_burned_area.jpeg/revision/latest?cb=20121007165231)

:D

**Comment by jorjo1** [comment]
Will do!

**Comment by jorjo1** [comment]
Done! Now I finally can close this one here. :surfer:
