### ISSUE TITLE
Map: Link "more Info" to our detail-page

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#80]
Should we link the "More Info" link on the map to our detail-page?

**Comment by jorjo1** [comment]
Yes, we should most definitely do it!
Any idea if we should edit the map or open an issue at Project C?

**Comment by yashha** [comment]
https://github.com/Rostlab/JS16_ProjectC_Group10/issues/180

**Comment by sacdallago** [comment]
Quick update: I has been ruled that **F** should do this ;)
Who was that static content responsible of yours? :P :P

**Comment by jorjo1** [comment]
@sacdallago @Andrew094

**Comment by gyachdav** [comment]
@Andrew094, any updates here? the map landmark pop ups still load with an error message instead of content. 

@AlexBeischl @mbandle @tPiffrader

**Comment by gyachdav** [comment]
C'mon guys.. why is this not handled?
