### ISSUE TITLE
CharacterStore uses the API wrong

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#89]
Update getCharacter in model
e.g. 
wrong: `https://got-api.bruck.me/api/characters/56ea4cff8c27d7c637505db5` 
right: `https://got-api.bruck.me/api/characters/byID/56ea4cff8c27d7c637505db5`

**Comment by mammuth** [comment]
afaik @mina-zaki discussed with the guys from A, that id'd be the best solution to query by name. Furthermore then we can use the names to identify the characters which is also more SEO-friendly.

**Comment by yashha** [comment]
Already in branch character-page-georgi fixed

**Comment by sacdallago** [comment]
Guys, also for you! Set up a config point where by changing just 1 LOC I can change from bruck's server to localhost:12345.

I'm gonna personally take down Bruck's server to make sure your babies (aka projects) can survive without their mama
