### ISSUE TITLE
Character-Listing: Search not only by name

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#99]
But also by culture and house.

so the internal filterCharacters() function needs to be updated.

**Comment by mina-kleid** [comment]
i have added the house and culture to the filter constants
@mammuth @jorjo1 sort and filter have to be in the following format, otherwise they will be ignored
filter has to have field and value, sort has to have field and type
 sort = {field: Constants.SORT_FIELD_NAME, type: Constants.SORT_TYPE_ASC};
 filter = {field: Constants.FILTER_FIELD_NAME ,value: "LyRI"};

**Comment by mammuth** [comment]
I haven't looked into the code, however this sounds like we can search for either name OR house right? 

However atm we only have one big search bar that should be able to search for everything you throw into it, so the user doesn't need to hassle around with filters. 

When the user enters a term, we can't provide your function with the information whether it's a name or a house. Your function should filter for both and merge the two results. 

I think this search is something we might make fancy improvements in the future (#fuzzy search), so it's actually_searching_ and not just strict _filtering_.

**Comment by mammuth** [comment]
Edit: to let the possibility for strict filters there, maybe just add a parameter "search" or "term" which is searched in all characters names, cultures and houses?

**Comment by mina-kleid** [comment]
@mammuth ok makes sense, will fix it

**Comment by mammuth** [comment]
:heart_eyes:

**Comment by mina-kleid** [comment]
So now here are how the filter and sort look like 
sort = {field: Constants.SORT_FIELD_NAME, type: Constants.SORT_TYPE_ASC};
filter = {value: "LyRI"};

if you want to skip any of them (i.e. no filter or sort), please provide empty objects {}

**Comment by jorjo1** [comment]
perfect! Can we close this one?

**Comment by jorjo1** [comment]
@yashha 
I found a bug when I search for names which contain special characters!
https://got-stats.herokuapp.com/characters/Rhaena%20Targaryen%20(daughter%20of%20Daemon) 
For example search for ( .. or sth else.

:exclamation: :exclamation: :exclamation: really important

**Comment by yashha** [comment]
https://github.com/Rostlab/JS16_ProjectA/issues/111

**Comment by mina-kleid** [comment]
Is this finished ?

**Comment by mammuth** [comment]
I guess so. If not it makes sense to open more specific issues. :+1:
